/**
 * Language file for Frost
 *
 * This file has been created automatically.
 * Do NOT edit unless you REALLY know what you're doing!
 *
 * Language: bg
 */

package res;

import java.util.ListResourceBundle;

public class LangRes_bg extends ListResourceBundle {

public Object[][] getContents() {
    return contents;
}

static final Object[][] contents = {
{"Requested","Requested"},
{"Remove selected files","Remove selected files"},
{"Help","Помощ"},
{"Waittime after each try","Waittime after each try"},
{"Send message","Send message"},
{"Should file attachments be added to upload table?","Should file attachments be added to upload table?"},
{"Hide unsigned messages","Hide unsigned messages"},
{"Public key","публичен ключ"},
{"Remove finished downloads every 5 minutes","Remove finished downloads every 5 minutes"},
{"splitfile explanation","(bigger is faster but uses more cpu)"},
{"Waiting","Waiting"},
{"New folder","New folder"},
{"Do spam detection","Do spam detection"},
{"Disable downloads","Disable downloads"},
{"Help spread files from people marked GOOD","Help spread files from people marked GOOD"},
{"Add new folder","Add new folder"},
{"No 'From' specified!","No 'From' specified!"},
{"Index","Индекс"},
{"Refresh folder","Refresh folder"},
{"Add Board(s)","Add Board(s)"},
{"Automatic Indexing","Automatic Indexing"},
{"Search","Search"},
{"RefreshList","Refresh List"},
{"Download selected keys","Download selected keys"},
{"New board","New board"},
{"Mark message unread","Mark message unread"},
{"Restart selected downloads","Restart selected downloads"},
{"Enable downloads","Enable downloads"},
{"Upload selected files","Upload selected files"},
{"Try to download all segments, even if one fails","Try to download all segments, even if one fails"},
{"CHK key","CHK key"},
{"Files","Файли"},
{"Remove","Изтрий"},
{"all boards","all boards"},
{"Status","Статус"},
{"Preview","Preview"},
{"Maximum number of retries","Maximum number of retries"},
{"Upload all files","Upload all files"},
{"Welcome message","Please read this!\n\nTo use Frost, you first need to select a topic from the board information window. You can openthis window with the i-button above. You can send messages and files to people using the same board. It will probably take some time until the first boards show up (press the update button)."},
{"German","German"},
{"Filename","Име на файл"},
{"Disable splashscreen","Disable splashscreen"},
{"OK","OK"},
{"Enable all downloads","Enable all downloads"},
{"Download all keys","Download all keys"},
{"MoreSkinsAt","You can get more skins at"},
{"AvailableSkins","Available Skins"},
{"Italian","Italian"},
{"Maximum search results","Maximum search results"},
{"Start encoding of selected files","Start encoding of selected files"},
{"Number of simultaneous downloads","Number of simultaneous downloads"},
{"Save message to disk","Save message to disk"},
{"Disable selected downloads","Disable selected downloads"},
{"Bulgarian","Български"},
{"up htl explanation","(bigger is slower but more reliable)"},
{"Generate new keypair","Generate new keypair"},
{"Hide files from anonymous users","Hide files from anonymous users"},
{"Uploads","Uploads"},
{"Remove board","Премахни борд"},
{"Enable selected downloads","Enable selected downloads"},
{"Executable Extension","Executable Extension"},
{"Restore default filenames for selected files","Restore default filenames for selected files"},
{"Threshold of blocked messages","Threshold of blocked messages"},
{"Translate Frost into another language","Translate Frost into another language"},
{"Add selected board","Add selected board"},
{"Secure board","Secure board"},
{"Increase Font Size","Increase Font Size"},
{"Upload batch size","Upload batch size"},
{"Sign","Sign"},
{"Update","Обнови"},
{"You must enter a subject!","You must enter a subject!"},
{"Trust","Trust"},
{"Number of days to download backwards","Number of days to download backwards"},
{"Cut board","Cut board"},
{"Choose background color if updating board is not selected","Choose background color if updating board is not selected"},
{"Age","Age"},
{"Plugins","Plugins"},
{"board","борд"},
{"Hide messages flagged N/A","Hide messages flagged N/A"},
{"No subject specified!","No subject specified!"},
{"Size","Размер"},
{"Number of splitfile threads","Number of splitfile threads"},
{"News","Съобщения"},
{"Invert enabled state for all downloads","Invert enabled state for all downloads"},
{"NoSkinsFound","No skins found!"},
{"Invert enabled state for selected downloads","Invert enabled state for selected downloads"},
{"Number of days to display","Number of days to display"},
{"Message upload HTL","Message upload HTL"},
{"Restart failed downloads","Restart failed downloads"},
{"Mark ALL messages read","Mark ALL messages read"},
{"Done","Готов"},
{"Do not trust","Do not trust"},
{"list of nodes","Comma-separated list of nodes you have FCP access to"},
{"About","Относно"},
{"Private key","Private key"},
{"Board Information Window","Board Information Window"},
{"Image Extension","Image Extension"},
{"Restore default filenames for all files","Restore default filenames for all files"},
{"Block messages with body containing (separate by ';' )","Block messages with body containing (separate by ';' )"},
{"Show healing information","Show healing information"},
{"Choose updating color of SELECTED boards","Choose updating color of SELECTED boards"},
{"BoardInfoFrame.UpdateSelectedBoardButton","Update Selected Board"},
{"Message base","Message base"},
{"Messages","Messages"},
{"minutes","minutes"},
{"Clean the keypool","Clean the keypool"},
{"Add new board","Add new board"},
{"Key","Ключ"},
{"Trying","Trying"},
{"Sample interval","Sample interval"},
{"Date","Дата"},
{"Options","Настройки"},
{"block user (sets to BAD)","block user (sets to BAD)"},
{"Display known boards","Display known boards"},
{"Index file redundancy","Index file redundancy"},
{"Signature","Подпис"},
{"You must enter a sender name!","You must enter a sender name!"},
{"Board","Борд"},
{"Enable requesting of failed download files","Enable requesting of failed download files"},
{"Upload HTL","Upload HTL"},
{"Minimum update interval of a board","Minimum update interval of a board"},
{"Audio Extension","Audio Extension"},
{"On","Вкл."},
{"Share Downloads","Share Downloads"},
{"Miscellaneous","Разни"},
{"Uploading","Uploading"},
{"Cancel","Отказ"},
{"State","State"},
{"Destination","Destination"},
{"Never","Never"},
{"Keyfile download HTL","Keyfile download HTL"},
{"Show systray icon","show SysTray icon"},
{"Results","Резултати"},
{"Board information","Board information"},
{"English","English"},
{"Path","Path"},
{"TOFDO","TOFDO"},
{"Please enter the prefix you want to use for your files.","Please enter the prefix you want to use for your files."},
{"Do you want to enter a subject?","Do you want to enter a subject?"},
{"Disable uploads","Disable uploads"},
{"Save message","Save message"},
{"Exit","Изход"},
{"Download directory","Download directory"},
{"Remove finished downloads","Remove finished downloads"},
{"Browse","Browse"},
{"Last upload","Last upload"},
{"Copy to clipboard","Copy to clipboard"},
{"Reply","Отговори"},
{"Document Extension","Document Extension"},
{"Spanish","Spanish"},
{"hours","hours"},
{"Keyfile upload HTL","Keyfile upload HTL"},
{"Maximum number of keys to store","Maximum number of keys to store"},
{"redundancy explanation","not working yet"},
{"Download attachment(s)","Download attachment(s)"},
{"New message","New message"},
{"Add attachment(s)","Add attachment(s)"},
{"Messages Today","Messages Today"},
{"Block messages with subject containing (separate by ';' )","Block messages with subject containing (separate by ';' )"},
{"Unknown","Unkown"},
{"Use editor for writing messages","Use editor for writing messages"},
{"File","File"},
{"MessageBodyFont","Message Body Font"},
{"Display list of known boards","Display list of known boards"},
{"TOFUP","TOFUP"},
{"Reload all files","Upload all files"},
{"Set prefix for all files","Set prefix for all files"},
{"Off","Изкл."},
{"Rename folder","Rename folder"},
{"Activate downloading","Activate downloading"},
{"help user (sets to GOOD)","help user (sets to GOOD)"},
{"Choose updating color of NON-SELECTED boards","Choose updating color of NON-SELECTED boards"},
{"Experimental Freenet Browser","Experimental Freenet Browser"},
{"French","French"},
{"Automatic update options","Automatic update options"},
{"Frost by Jantho","Frost by Jantho"},
{"Public board","Public board"},
{"Preferences","Preferences"},
{"Remove all downloads","Remove all downloads"},
{"Down","Долу"},
{"New Node Name","New Board name"},
{"Request file after this count of retries","Request file after this count of retries"},
{"Archive Extension","Archive Extension"},
{"Indexed attachments","Indexed attachments"},
{"Subject","Subject"},
{"Select a message to view its content.","Select a message to view its content."},
{"Automatic message update","Automatic board update"},
{"Failed","Failed"},
{"Selected board","Selected board"},
{"Choose background color if updating board is selected","Choose background color if updating board is selected"},
{"Configure selected board","Configure selected board"},
{"Remove selected downloads","Remove selected downloads"},
{"Display board information window","Display board information window"},
{"Dutch","Dutch"},
{"Show board update visualization","Show board update visualization"},
{"Decode each segment immediately after its download","Decode each segment immediately after its download"},
{"Disable all downloads","Disable all downloads"},
{"Set prefix for selected files","Set prefix for selected files"},
{"Display","Display"},
{"Sign shared files","Sign shared files"},
{"Japanese","Japanese"},
{"Create message","Create message"},
{"Language","Language"},
{"Choose boards to attach","Choose boards to attach"},
{"Hide files from people marked BAD","Hide files from people marked BAD"},
{"Boards","Boards"},
{"Paste board","Paste board"},
{"Minimize to System Tray","Minimize to System Tray"},
{"batch explanation","bigger is faster but smaller is spam resistant"},
{"Number of concurrently updating boards","Number of concurrently updating boards"},
{"Video Extension","Video Extension"},
{"Message download HTL","Message download HTL"},
{"Hide messages flagged BAD","Hide messages flagged BAD"},
{"From","From"},
{"Choose file(s) / directory(s) to attach","Choose file(s) / directory(s) to attach"},
{"Select file you want to upload to the","Select file you want to upload to the"},
{"Hide messages flagged CHECK","Hide messages flagged CHECK"},
{"Up","Up"},
{"Downloads","Downloads"},
{"Source","Source"},
{"Decrease Font Size","Decrease Font Size"},
{"Configure board","Configure board"},
{"Change destination board","Change destination board"},
{"CHK key + filename","CHK key + filename"},
{"EnableSkins","Enable Skins"},
{"Number of simultaneous uploads","Number of simultaneous uploads"},
{"Allow 2 byte characters","Allow 2 byte characters"},
{"Reload selected files","Upload selected files"},
{"Automatic saving interval","Automatic saving interval"},
{"Remove all files","Remove all files"},
{"Not available","Not available"},
{"Set to CHECK","Set to CHECK"},
};
}
