/**
 * Language file for Frost
 *
 * This file has been created automatically.
 * Do NOT edit unless you REALLY know what you're doing!
 *
 * Language: ja
 */

package res;

import java.util.ListResourceBundle;

public class LangRes_ja extends ListResourceBundle {

public Object[][] getContents() {
    return contents;
}

static final Object[][] contents = {
{"About","Frost について"},
{"Activate downloading","ダウンロードを有効に"},
{"Add attachment(s)","ファイルの添付"},
{"Add Board(s)","板を追加"},
{"Add new board","新たな板を追加"},
{"Add new folder","新たなフォルダを追加"},
{"Add selected board","選択された板を追加"},
{"Age","更新日"},
{"all boards","全ての板"},
{"All files","全てのファイル"},
{"Allow 2 byte characters","2バイト文字を使用する"},
{"Archive Extension","アーカイブの拡張子"},
{"Archives","アーカイブ"},
{"Audio","オーディオ"},
{"Audio Extension","オーディオの拡張子"},
{"Automatic Indexing","自動インディクス化"},
{"Automatic message update","板を自動更新"},
{"Automatic saving interval","自動保存の間隔"},
{"Automatic update options","オプションの自動更新間隔"},
{"AvailableSkins","利用可能なスキン"},
{"batch explanation","大きければ高速だが小さければスパム対抗性がある"},
{"Block messages with body containing (separate by ';' )","この文字列を本文に含む投稿を抹消 (';'で区切る)"},
{"Block messages with subject containing (separate by ';' )","この文字列を題名に含む投稿を抹消 (';'で区切る)"},
{"block user (sets to BAD)","この人物を排除 (BADに設定)"},
{"Blocks","ブロック"},
{"board","板"},
{"Board","板"},
{"Board Information Window","板情報ウインドウ"},
{"BoardInfoFrame.Board information window","板情報ウインドウ"},
{"BoardInfoFrame.Boards","板"},
{"BoardInfoFrame.Close","閉じる"},
{"BoardInfoFrame.Files","ファイル"},
{"BoardInfoFrame.Messages","投稿"},
{"BoardInfoFrame.Update","更新"},
{"BoardInfoFrame.Update all boards","全ての板を更新"},
{"BoardInfoFrame.UpdateSelectedBoardButton","この板を更新"},
{"Browse","ブラウズ"},
{"Bulgarian","ブルガリア語"},
{"Cancel","キャンセル"},
{"Change destination board","送信先の板を変える"},
{"Copy keys only","CHKキー"},
{"Copy keys with filenames","CHKキー + ファイル名"},
{"Choose boards to attach","付記する板を選択して下さい"},
{"Choose file(s) / directory(s) to attach","添付するファイルまたはディレクトリを選択"},
{"Choose updating color of NON-SELECTED boards","更新中の板が選択されていない時の色"},
{"Choose updating color of SELECTED boards","更新中の板が選択されている時の色"},
{"Clean the keypool","キープールを消去"},
{"Configure board","板の設定"},
{"Configure selected board","この板の設定"},
{"Copy to clipboard","クリップボードにコピー"},
{"Create message","投稿の作成"},
{"Cut","カット"},
{"Cut board","板をカット"},
{"Date","日付"},
{"Decode each segment immediately after its download","各部分をダウンロード終了後に即座にデコードする"},
{"Decrease Font Size","フォントサイズを小さく"},
{"Default","デフォルト"},
{"Destination","送信先"},
{"Disable all downloads","全てのダウンロードを無効に"},
{"Disable downloads","ダウンロードを無効に"},
{"Disable selected downloads","選択されたダウンロードを無効に"},
{"Disable splashscreen","スプラッシュスクリーンを表示しない"},
{"Disable uploads","アップロードを無効に"},
{"Display","表示"},
{"Display board information window","板情報ウインドウを表示"},
{"Display known boards","既知の板を表示"},
{"Display list of known boards","既知の板のリストを表示"},
{"Do not trust","信用しない"},
{"Do spam detection","スパム検出を行う"},
{"Do you want to enter a subject?","題名を決めますか?"},
{"Document Extension","文書の拡張子"},
{"Documents","文書"},
{"Done","完了"},
{"Down","下り"},
{"Download all keys","全てのキーをダウンロード"},
{"Download attachment(s)","添付ファイルのダウンロード"},
{"Download directory","ダウンロード先ディレクトリ"},
{"Download selected attachment","この添付ファイルをダウンロード"},
{"Download selected keys","このキーをダウンロード"},
{"Downloads","ダウンロード"},
{"Dutch","オランダ語"},
{"Enable all downloads","全てのダウンロードを有効に"},
{"Enable downloads","ダウンロードを開始"},
{"Enable requesting of failed download files","ダウンロードに失敗したファイルをリクエストする"},
{"Enable selected downloads","このダウンロードを有効に"},
{"EnableSkins","スキンを有効に"},
{"English","英語"},
{"Executable Extension","実行形式の拡張子"},
{"Executables","実行形式"},
{"Exit","終了"},
{"Experimental Freenet Browser","試験的Freenetブラウザ"},
{"Failed","失敗"},
{"File","ファイル"},
{"Filename","ファイル名"},
{"Files","ファイル"},
{"Folder","フォルダ"},
{"folder","フォルダ"},
{"French","フランス語"},
{"From","投稿者"},
{"Generate new keypair","新たな鍵ペアの作成"},
{"German","ドイツ語"},
{"Help","ヘルプ"},
{"Help spread files from people marked GOOD","GOODと評価された人々によるファイルの流通を助ける"},
{"help user (sets to GOOD)","この人物を助ける (GOODに設定)"},
{"Hide files from anonymous users","匿名の人物によるファイルを表示しない"},
{"Hide files from people marked BAD","BADと評価された人物によるファイルを表示しない"},
{"Hide messages flagged BAD","BADと判定された投稿を表示しない"},
{"Hide messages flagged CHECK","CHECKと判定された投稿を表示しない"},
{"Hide messages flagged N/A","N/Aと判定された投稿を表示しない"},
{"Hide unsigned messages","署名されていない投稿を表示しない"},
{"hours","時間"},
{"Image Extension","画像の拡張子"},
{"Images","画像"},
{"Increase Font Size","フォントサイズを大きく"},
{"Index","インディクス"},
{"Index file redundancy","インディクスファイルの冗長度"},
{"Indexed attachments","添付ファイルをインディクス化"},
{"Invert enabled state for all downloads","全てのダウンロードの有効性を反転"},
{"Invert enabled state for selected downloads","このダウンロードの有効性を反転"},
{"Italian","イタリア語"},
{"Japanese","日本語"},
{"Key","キー"},
{"Keyfile download HTL","キーファイルのダウンロードHTL"},
{"Keyfile upload HTL","キーファイルのアップロードHTL"},
{"KnownBoardsFrame.Add board","板を追加"},
{"KnownBoardsFrame.Close","閉じる"},
{"KnownBoardsFrame.List of known boards","既知の板のリスト"},
{"KnownBoardsFrame.Lookup","検索"},
{"KnownBoardsFrame.Remove board","板を削除"},
{"Language","言語"},
{"Last upload","更新日"},
{"list of nodes","FCP接続を行うノードのリスト (カンマ区切り)"},
{"Mark ALL messages read","全ての投稿を既読に"},
{"Mark message unread","この投稿を未読に"},
{"Maximum number of keys to store","保存するキーの最大数"},
{"Maximum number of retries","最大リトライ回数"},
{"Maximum search results","最大検索件数"},
{"Message base","投稿のベース"},
{"Message download HTL","投稿のダウンロードHTL"},
{"Message upload HTL","投稿のアップロードHTL"},
{"Messages","投稿"},
{"Messages Today","今日の投稿"},
{"Minimize to System Tray","システムトレイに最小化"},
{"Minimum update interval of a board","板の最短更新間隔"},
{"minutes","分"},
{"Miscellaneous","いろいろな設定"},
{"MoreSkinsAt","その他のスキンの取得先:"},
{"Never","未送信"},
{"New board","板を追加"},
{"New folder","フォルダを追加"},
{"New message","投稿"},
{"New Node Name","新たな板の名前"},
{"News","ニュース"},
{"No 'From' specified!","投稿者名が入力されていません"},
{"No subject specified!","題名が入力されていません"},
{"NoSkinsFound","スキンが見付かりません"},
{"Not available","利用不可"},
{"Number of concurrently updating boards","同時に更新する板の数"},
{"Number of days to display","表示する日数"},
{"Number of days to download backwards","過去に遡ってダウンロードする日数"},
{"Number of simultaneous downloads","同時ダウンロード数"},
{"Number of simultaneous uploads","同時ダウンロード数"},
{"Number of splitfile threads","ファイル分割スレッドの数"},
{"Off","オフ"},
{"OK","OK"},
{"On","オン"},
{"Options","オプション"},
{"Paste","ペースト"},
{"Paste board","板をペースト"},
{"Path","パス"},
{"Pause downloading","ダウンロードを一時中断"},
{"Please enter the prefix you want to use for your files.","ファイル名の頭につけたい言葉を入力してください。"},
{"Plugins","プラグイン"},
{"Preferences","設定"},
{"Preview","プレビュー"},
{"Private key","秘密鍵"},
{"Public board","自由な投稿を許可する"},
{"Public key","公開鍵"},
{"redundancy explanation","not working yet"},
{"Refresh","更新"},
{"RefreshList","リストを更新"},
{"Reload all files","全項目の再アップロード"},
{"Reload selected files","選択項目の再アップロード"},
{"Remove","削除"},
{"Remove all downloads","全項目をリストから削除"},
{"Remove all files","全項目をリストから削除"},
{"Remove board","板を削除"},
{"Remove finished downloads","終了したダウンロード項目を削除"},
{"Remove finished downloads every 5 minutes","終了したダウンロード項目を五分毎に削除"},
{"Remove selected downloads","選択項目をリストから削除"},
{"Remove selected files","選択項目をリストから削除"},
{"Rename folder","フォルダ名を変更"},
{"Reply","返信"},
{"Request file after this count of retries","この回数を再試行した後、ファイルをリクエストする"},
{"Requested","リクエスト"},
{"Restart failed downloads","失敗したダウンロードをやり直す"},
{"Restart selected downloads","このダウンロードをやり直す"},
{"Restore default filenames for all files","全項目の名前を元に戻す"},
{"Restore default filenames for selected files","選択項目の名前を元に戻す"},
{"Results","結果"},
{"Sample interval","サンプル間隔"},
{"Save message","投稿を保存"},
{"Save message to disk","この投稿をディスクに保存"},
{"Search","検索"},
{"Secure board","暗号鍵で投稿を制限する"},
{"Select a message to view its content.","見たい投稿を選んでください"},
{"Select download directory","ダウンロード先ディレクトリを選択"},
{"Select files you want to upload to the","アップロードするファイルを選択:"},
{"Selected board","選択された板"},
{"Send message","投稿"},
{"Set prefix for all files","全項目の名前に接頭語をつける"},
{"Set prefix for selected files","選択項目の名前に接頭語をつける"},
{"Set to CHECK","CHECKに設定"},
{"set to neutral (CHECK)","中立に設定 (CHECK)"},
{"Share Downloads","ダウンロードしたファイルを共有"},
{"Should file attachments be added to upload table?","添付ファイルをアップロード表に追加しますか？"},
{"Show board update visualization","板の更新を視覚化"},
{"Show healing information","修復情報を表示"},
{"Show systray icon","システムトレイアイコンを表示"},
{"Sig","署名"},
{"Sign","署名"},
{"Sign shared files","共有ファイルに署名する"},
{"Signature","シグネチャ"},
{"Size","サイズ"},
{"Sort folder","フォルダをソート"},
{"Source","ソース"},
{"Spanish","スペイン語"},
{"splitfile explanation","(大きな方が速いがCPUをより使う)"},
{"Start encoding of selected files","選択されたファイルのエンコードを開始"},
{"State","状況"},
{"Status","状況"},
{"Subject","題名"},
{"Threshold of blocked messages","投稿排除の閾値"},
{"TOFDO","TOFDO"},
{"TOFUP","TOFUP"},
{"Translate Frost into another language","Frostを他の言語に翻訳する"},
{"Tries","試行"},
{"Trust","信用"},
{"Try to download all segments, even if one fails","一部分が落とせなくても全ての部分を落とそうと試みる"},
{"Trying","開始"},
{"Unknown","未知"},
{"Up","上り"},
{"up htl explanation","(大きければ時間がかかるが確実)"},
{"Update","更新"},
{"Upload all files","全ファイルをアップロード"},
{"Upload batch size","アップロードのバッチサイズ"},
{"Upload HTL","アップロードHTL"},
{"Upload selected files","投稿の作成に用いるエディタ"},
{"Uploading","送信中"},
{"Uploads","アップロード"},
{"Use editor for writing messages","投稿の作成に用いるエディタ"},
{"Video","動画"},
{"Video Extension","動画の拡張子"},
{"Waiting","待機中"},
{"Waittime after each try","各試行の待ち時間"},
{"Welcome message","お読み下さい！ Frostを使うには、まず板情報ウインドウからトピックを選択する必要があります。このウインドウは上部の i ボタンで開けます。投稿やファイルは、同じ板を使っている人々にのみ送る事が出来ます。最初に板が表示されるまで、多少の時間がかかるかも知れません(更新ボタンを押して下さい)。"},
{"You must enter a sender name!","投稿者名を入力して下さい。"},
{"You must enter a subject!","題名を入力して下さい。"},
};
}
