/**
 * Language file for Frost
 *
 * This file has been created automatically.
 * Do NOT edit unless you REALLY know what you're doing!
 *
 * Language: fr
 */

package res;

import java.util.ListResourceBundle;

public class LangRes_fr extends ListResourceBundle {

public Object[][] getContents() {
    return contents;
}

static final Object[][] contents = {
{"MessageFrame.ConfirmBody2","'.  Êtes-vous sûr que vous voulez attacher la clef privée ? Si vous choisissez NON, seule la clef publique sera jointe."},
{"up htl explanation","(un HTL élevé est plus lent mais plus fiable)"},
{"list of nodes 2","(noeudA:portA, noeudB:portB, ...)"},
{"splitfile explanation","(plus grand est plus rapide mais utilise plus de CPU)"},
{"About","A propos"},
{"Access rights","Access rights"},
{"EnableMessageBodyAA","Activer l'anticrénelage pour le corps des messages"},
{"Enable automatic board update","Activer le rafraichissement automatique des forums"},
{"Activate downloading","Activer le téléchargement"},
{"EnableSkins","Activer les Skins"},
{"Enable all downloads","Activer tous les téléchargements"},
{"Enable selected downloads","Activer tous les téléchargements sélectionnés"},
{"Enable downloads","Activer téléchargements"},
{"Maximum message display (days)","Affichage maximum des messages (En jours)"},
{"Display","Afficher"},
{"Display board information window","Afficher la fenetre d'infos des boards"},
{"Display list of known boards","Afficher la liste des boards connues"},
{"Display known boards","Afficher les boards connues"},
{"Age","Age"},
{"Help","Aide"},
{"Help spread files from people marked GOOD","Aider les personnes notés GOOD"},
{"help user (sets to GOOD)","Aider l'utilisateur (noter GOOD)"},
{"KnownBoardsFrame.Add board","Ajouter board"},
{"NewBoardDialog.add","Ajouter Board"},
{"Add selected board","Ajouter la board"},
{"Add new folder","Ajouter un repertoire"},
{"Add new board","Ajouter une board"},
{"NewBoardDialog.title","Ajouter une nouvelle board"},
{"German","Allemand"},
{"English","Anglais"},
{"Cancel","Annuler"},
{"FrostSearchItemObject.Anonymous","Anonyme"},
{"Automatic update options","Appliquer automatiquement les options"},
{"Archive Extension","Extension fichiers archive"},
{"Archives","Archives"},
{"Core.init.NodeNotRunningBody","Assurez-vous que votre noeud fonctionne et que vous avez configuré freenet correctement."},
{"No 'From' specified!","Aucun 'From' n'est indiqué !"},
{"No subject specified!","Aucun sujet spécifié!"},
{"NoSkinsFound","Aucun Skin trouvée"},
{"Audio","Audio"},
{"Audio Extension","Extension fichiers audio"},
{"Increase Font Size","Augmentez La Taille de Police"},
{"From","Auteur"},
{"Automatic saving interval","Intervale d'enregistrement automatique"},
{"Allow 2 byte characters","Autoriser les caracteres de 2 octets"},
{"Warning","Avertissement"},
{"Background color if updating board is not selected","Couleur de fond si la board mise à jour n'est pas sélectionnée"},
{"Background color if updating board is selected","Couleur de fond si la board mise à jour est sélectionnée"},
{"Low","Bas"},
{"Message base","Base de message"},
{"batch explanation","Une valeur élevée est plus rapide mais une valeur faible résiste au spam"},
{"Blocks","Blocks"},
{"Block messages with these attached boards (separate by ';' )","Bloquer les messages ayant ces boards en piece jointe(separate by ';' )"},
{"Block messages with subject containing (separate by ';' )","Bloquer les messages ayant pour sujet (separate by ';' )"},
{"Block messages with body containing (separate by ';' )","Bloquer les messages contenants (separate by ';' )"},
{"block user (sets to BAD)","Bloquer l'utilisateur (noter BAD)"},
{"board","board"},
{"Board","Board"},
{"Board Information Window","Fenêtre d'information sur la board"},
{"BoardInfoFrame.Board information window","Fenêtre d'information sur la board"},
{"Board Name","Nom de la board"},
{"Selected board","Board selectionnée"},
{"BoardInfoFrame.Boards","Boards"},
{"Experimental Freenet Browser","Browser Expérimental de Freenet"},
{"Bulgarian","Bulgare"},
{"clipboard.Bytes:","Octets: "},
{"Hide files from anonymous users","Cacher les fichiers des utilisateurs anonymes"},
{"Hide files from people marked BAD","Cacher les fichiers des utilisateurs BAD"},
{"Hide messages flagged BAD","Cacher les messages marqué BAD"},
{"Hide messages flagged CHECK","Cacher les messages marqué CHECK"},
{"Hide messages flagged N/A","Cacher les messages marqué N/A"},
{"Hide unsigned messages","Cacher les messages non signés"},
{"This will not delete messages","Ceci ne supprimera pas de messages"},
{"Change destination board","Changer la board de destination"},
{"Path","Chemin"},
{"Choose","Choisir"},
{"Choose updating color of NON-SELECTED boards","Choisir la couleur utilisé pendant le rafraichissement des boards non-sélectionnées"},
{"Choose updating color of SELECTED boards","Choisir la couleur utilisé pendant le rafraichissement des boards sélectionnées"},
{"Select download directory","Choisir le repertoire de téléchargement"},
{"Choose boards to attach","Choisir les boards à joindre"},
{"Select files you want to upload to the","Choisir les fichiers à insérer"},
{"Choose a Font","Choisir une police"},
{"Core.loadIdentities.ChooseName","Choisissez un pseudo, il ne doit pas être obligatoirement unique "},
{"Select a board to view its content.","Choisissez une board pour voir son contenu"},
{"Sort folder","Classer les répertoires"},
{"Clean the keypool","Nettoyer les anciennes clefs"},
{"Key","Clef"},
{"Copy keys only","Clef CHK"},
{"Copy keys with filenames","Clef CHK + nom du fichier"},
{"Private key","Clef privée"},
{"Public key","Clef publique"},
{"Encode requested","Encodage nécessaire"},
{"Paste","Coller"},
{"Paste board","Coller board"},
{"Color","Couleur"},
{"list of nodes","Liste des noeuds (séparés par des virgules) auxquels vous avez accès"},
{"Start encoding of selected files","Commencer l'encodage des fichiers sélectionnés"},
{"Configure board","Configurer cette board"},
{"Configure selected board","Configurer la board sélectionnée"},
{"KnownBoardsFrame.Lookup","Consulter"},
{"Copy to clipboard","Copier dans le presse papier"},
{"Copy","Copier"},
{"Copy extended info","Copier les informations "},
{"Message Body","Corps de message"},
{"Cut","Couper"},
{"Cut board","Couper board"},
{"Date","Date"},
{"Delete message","Supprimer message"},
{"Last upload","Dernier envoi"},
{"Description","Description"},
{"NewBoardDialog.description","Description (Facultative). Ne mettez pas d'information privée ici :"},
{"BoardSettingsFrame.description","Description:"},
{"Destination","Destination"},
{"Do spam detection","Detecter le Spam"},
{"Development:","Developpement:"},
{"Decrease Font Size","Diminuez La Taille de Police"},
{"Discard message","Ignorer message"},
{"Miscellaneous","Divers"},
{"Document Extension","Extension de documents"},
{"Documents","Documents"},
{"Down","Down"},
{"DownloadStatusPanel.Downloading","Téléchargement:"},
{"Decode each segment immediately after its download","Décoder chaque segment juste après son téléchargement"},
{"Decoding segment","Décodage du segment"},
{"Default","Défaut "},
{"Set prefix for all files","Définir le préfixe de tous les fichiers"},
{"Set prefix for selected files","Définir le préfixe des fichiers sélectionnés"},
{"Disable splashscreen","Désactiver le splashscreen"},
{"Disable uploads","Désactiver les envois"},
{"Disable downloads","Désactiver les téléchargements"},
{"Failed","Echoué"},
{"Remove selected files","Effacer les fichiers sélectionnés"},
{"Remove selected downloads","Effacer les téléchargements sélectionnés"},
{"Remove all files","Effacer tous les fichiers"},
{"Remove all downloads","Effacer tous les téléchargements"},
{"Waiting","En attente"},
{"redundancy explanation","En devellopement"},
{"FrostSearchItemObject.Offline","En différé"},
{"Enable logging","Activer la journalisation"},
{"Enable requesting of failed download files","Demander les fichiers dont le téléchargement a échoué"},
{"DownloadTableFormat.Enabled","Activé"},
{"Save message to disk","Enregistrer ce message sur le disque..."},
{"Uploading","Envoi en cours"},
{"Sending IP address to NSA","Envoie l'adresse IP à la DST ;-)"},
{"Uploads","Insertions"},
{"Send message","Envoyer le message"},
{"Email.address","envoyez message à"},
{"Core.init.NodeNotRunningTitle","Erreur - impossible d'établir une liaison avec le noeud Freenet."},
{"Spanish","Espagnol"},
{"Trying","Essai en cours"},
{"Try to download all segments, even if one fails","Essayez de télécharger tous les segments, même si un échoue"},
{"Executable Extension","Extension fichers exécutables"},
{"Executables","Exécutables"},
{"Trust","Faire confiance"},
{"BoardInfoFrame.Close","Fermer"},
{"KnownBoardsFrame.Close","Fermer"},
{"File","Fichier"},
{"Encoding file","Fichier en cours d'encodage"},
{"BoardInfoFrame.Files","Fichiers"},
{"Files","Fichiers"},
{"StatusPanel.file","fichier"},
{"clipboard.File:","Fichier: "},
{"StatusPanel.files","fichiers"},
{"Public board","Board publique"},
{"Secure board","Board sécurisé"},
{"News","Forums"},
{"Number of concurrently updating boards","forums mis à jour simultanement"},
{"French","Francais"},
{"Saver.AutoTask.message","Frost a détecté une erreur et s'est fermé automatiquement."},
{"Core.loadIdentities.ConnectionNotEstablishedBody","Frost n'a pas pu établir une connexion avec le noeud freenet.\nCette connexion est nécessaire pour l'installation de Frost et la création de votre pseudo,\nensuite vous pourez lire les messages sans connexion. Veuillez vous assurer que vous êtes connecté puis relancez Frost."},
{"Frost was not able to upload your message.","Frost n'a pas pu envoyer ce message."},
{"Bold","Gras"},
{"Bold Italic","Gras Italique"},
{"Generate new keypair","Générer une nouvelle paire de clefs"},
{"High","Haut"},
{"hours","heures"},
{"Dutch","Hollandais"},
{"Message upload HTL","HTL d'insertion des messages"},
{"Keyfile upload HTL","HTL d'insertion"},
{"Message download HTL","HTL de Téléchargement des messages"},
{"Keyfile download HTL","HTL de Téléchargement."},
{"Hypercube fluctuating!","Fluctuation de l'hypercube !"},
{"Image Extension","Extension fichiers images"},
{"Images","Images"},
{"MessageFrame.ConfirmTitle","Inclure la clef privée ?"},
{"Unknown","Inconnu"},
{"Index","Index"},
{"Index file redundancy","Redondance des fichiers d'index"},
{"Automatic Indexing","Indexage Automatique"},
{"Indexed attachments","Indexage des fichiers/board attachés"},
{"Not available","Indisponible"},
{"Minimum update interval of a board","Intervalle minimum de mise à jour d'une board"},
{"Invert enabled state for selected downloads","Inversez l'état d'activation pour les téléchargements sélectionnés"},
{"Invert enabled state for all downloads","Inversez l'état d'activation pour tous les téléchargements"},
{"Italian","Italien"},
{"Italic","Italique"},
{"Never","Jamais"},
{"Japanese","Japonais"},
{"Add attachment(s)","Joindre"},
{"Add Board(s)","Joindre Board(s)"},
{"Key not available yet","Clef pas encore disponible"},
{"clipboard.Key:","Clef::   "},
{"Core.loadIdentities.ConnectionNotEstablishedTitle","La connection a Freenet a échoué"},
{"Language","Langue"},
{"Less","Moins"},
{"File List","Liste des fichiers"},
{"Message List","Liste des Messages"},
{"KnownBoardsFrame.List of known boards","Liste des boards connus"},
{"Log file size limit (in KB)","Limiter la taille du fichier journal (en KB)"},
{"Logging level","Niveau de journalisation"},
{"Mark message unread","Marquer ce message non-lu"},
{"Mark ALL messages read","Marquer TOUS LES messages lus"},
{"BoardInfoFrame.Messages","Messages"},
{"Messages","Messages"},
{"Messages Today","Messages d'Aujourd'hui"},
{"Update","Mettre à jour"},
{"Medium","Moyen"},
{"minutes","minutes"},
{"Misc code contributions:","Contributions diverses au code:"},
{"Override default settings","Modifier les paramètres par défaut"},
{"More","Plus"},
{"SMTP.password","mot de passe"},
{"Do not trust","Ne pas faire confiance"},
{"Core.init.TransientNodeTitle","Noeud transient detecté"},
{"KnownBoardsTableModel.Boardname","Nom de la Board"},
{"Filename","Nom du fichier"},
{"NewBoardDialog.name","Nom:"},
{"Number of simultaneous uploads","Nombre d'insertions simultanées"},
{"Number of days to display","Nombre de jours d'affichage"},
{"Number of splitfile threads","Nombre de threads consacrés au splitfile"},
{"Number of simultaneous downloads","Nombre de téléchargements simultanés"},
{"Maximum number of retries","Nombre maximum de tentatives"},
{"Maximum number of keys to store","Nombre maximum des clefs stockées"},
{"No","Non"},
{"Create message","Nouveau message"},
{"New message","Nouveau message"},
{"New Node Name","Nouveau nom de noeud"},
{"New Folder Name","Nouveau nom de repertoire"},
{"New folder","Nouveau repertoire"},
{"newfolder","Nouveau repertoire"},
{"New board","Nouvelle board"},
{"newboard","Nouvelle Board"},
{"Number of days to download backwards","Nombre de jours à récupérer dans le passé"},
{"Off","Off"},
{"OK","Ok"},
{"On","On"},
{"Open Source Project (GPL license)","Projet Open Source (license GPL)"},
{"Settings for board","Options de la board"},
{"Options","Options"},
{"Yes","Oui"},
{"Browse","Parcourir"},
{"Share Downloads","Partager les fichiers téléchargés"},
{"BoardSettingsFrame.confirmTitle","Placer cette Board en public ? "},
{"Plain","Plein"},
{"Plugins","Plugins"},
{"Fonts","Polices"},
{"Preview","Aperçu"},
{"Saver.AutoTask.title","Problème découvert."},
{"Preferences","Préférences"},
{"SMTP.username","pseudo"},
{"Core.loadIdentities.InvalidNameTitle","Pseudo invalide"},
{"UploadsUnderway.body","Quelques messages sont toujours en envois. Voulez-vous vraiment quitter ?"},
{"Exit","Quitter"},
{"BoardInfoFrame.Update","Rafraîchir"},
{"Refresh","Rafraîchir"},
{"Automatic message update","Rafraîchir automatiquement les boards"},
{"BoardInfoFrame.UpdateSelectedBoardButton","Rafraîchir les boards sélectionnées"},
{"RefreshList","Rafraîchir Liste"},
{"BoardInfoFrame.Update all boards","Rafraîchir tous les forums"},
{"Reaching ridiculous speed...","Message inutile..."},
{"Reload selected files","Recharger les fichiers sélectionnés"},
{"Reload all files","Recharger tous les fichiers"},
{"Search","Recherche"},
{"Restart failed uploads","Relancer les envois loupés"},
{"Silently retry failed messages","Relancer les messages loupés sans PopUp"},
{"Restart failed downloads","Relancer les téléchargements loupés"},
{"Restart selected downloads","Relancer les téléchargements selectionnés"},
{"Rename folder","Renommer répertoire"},
{"Folder","Répertoire"},
{"folder","répertoire"},
{"Request file after this count of retries","Demander les fichiers après x essais"},
{"Requested","Demandé"},
{"Requesting","Demande"},
{"Restore default filenames for all files","Restaurer les noms de fichiers par défaut de tous les fichiers"},
{"Restore default filenames for selected files","Restaurer les noms de fichiers par défaut des fichiers sélectionnés"},
{"Results","Resultats"},
{"Retry","Nouvelle tentative"},
{"Retry on next startup","Nouvelle tentative au prochain demarrage"},
{"Minimize to System Tray","Réduire dans le System Tray"},
{"Download directory","Répertoire de téléchargement"},
{"Reply","Répondre"},
{"Maximum search results","Résultats maximum de recherche"},
{"Sample","Exemple"},
{"Save message","Sauvegarder le message"},
{"SMTP.server","Adresse du serveur"},
{"Set to","Mettre"},
{"Set to CHECK","Mettre à CHECK"},
{"set to neutral (CHECK)","Mettre à neutre (CHECK)"},
{"Threshold of blocked messages","Seuil des messages bloqués "},
{"Should file attachments be added to upload table?","Les fichiers attachés doivent-ils être insérés ?"},
{"Show healing information","Montrer les informations de heal"},
{"BoardSettingsFrame.confirmBody","Si vous placez cette Board en public, vous perdrez ses clefs. Êtes-vous sûr de vouloir faire cela ?"},
{"Sig","Sig"},
{"Signature","Signature"},
{"Sign","Signer"},
{"Sign shared files","Signer les fichiers partagés"},
{"AvailableSkins","Skins Disponibles"},
{"Source","Source"},
{"Splash Screen Logo:","Splash Screen Logo:"},
{"Status","Etat"},
{"Disable selected downloads","Stopper les téléchargements sélectionnés"},
{"Disable all downloads","Stopper tous les téléchargements"},
{"Subject","Sujet"},
{"Remove","supprimer"},
{"KnownBoardsFrame.Remove board","Supprimer board"},
{"Remove board","Supprimer board"},
{"Remove finished downloads","Supprimer les téléchargements finis"},
{"Remove finished downloads every 5 minutes","Supprimer les téléchargements finis toutes les 5 minutes "},
{"System Tray Executables:","System Tray Executables:"},
{"Choose file(s) / directory(s) to attach","Sélectionnez le(s) fichier(s) / dossier(s) à joindre"},
{"Select a message to view its content.","Sélectionnez un message pour voir son contenu."},
{"Size","Taille"},
{"Waittime after each try","Temps d'attente après chaque essai"},
{"Done","Terminé"},
{"Frost.lockFileFound","Il semble que Frost soit déja démarré dans ce répertoire.\nDémarrer plusieurs Frost à partir du même répertoire cause des pertes de données.\nSi vous êtes VRAIMENT CERTAIN que Frost ne tourne pas déja, vous pouvez supprimer le fichier verrou :\n"},
{"TOFDO","TOFDO"},
{"TOFUP","TOFUP"},
{"All files","Tous les fichiers"},
{"Sample interval","Toutes les"},
{"all boards","Toutes les boards"},
{"Translate Frost into another language","Traduire Frost dans une autre langue"},
{"Translation Support:","Système de traduction:"},
{"Tries","Essais"},
{"Very low","Très bas"},
{"Very high","Très haut"},
{"SearchTableFormat.Downloading","Téléchargement "},
{"Pause downloading","Téléchargement en pause"},
{"Downloads","Téléchargements"},
{"Download attachment(s)","Télécharger la(les) pièce(s) jointe(s)"},
{"Download selected attachment","Télécharger la(les) pièce(s) jointe(s) sélectionnée(s)"},
{"Download selected keys","Télécharger les clefs sélectionnées"},
{"Download all keys","Télécharger toutes les clefs"},
{"SearchTableFormat.Downloaded","Téléchargé"},
{"You must enter a subject!","Un sujet est indispensable !"},
{"Undelete message","Récupérer le message"},
{"Initializing Mainframe","Initialisation du super-calculateur"},
{"Up","Up"},
{"Upload batch size","Taille du batch d'insertion"},
{"Upload HTL","HTL d'insertion"},
{"Upload of message failed","Echec de l'insertion du message"},
{"Upload selected files","Insérer les fichiers selectionnés"},
{"Upload all files","Insérer tous les fichiers"},
{"SearchTableFormat.Uploading","Insertion"},
{"UploadStatusPanel.Uploading","Insertion:"},
{"UploadsUnderway.title","Insertions en cours"},
{"Use default","Utiliser la valeur par défaut"},
{"Use editor for writing messages","Utiliser un éditeur de texte pour écrire les messages"},
{"Version","Version"},
{"Please choose a new name","Veuillez choisir un nouveau nom"},
{"Please enter the prefix you want to use for your files.","Veuillez entrer le préfixe que vous voulez utiliser pour vos fichiers."},
{"NewBoardDialog.details","Veuillez entrer les détails de la nouvelle board:"},
{"Welcome message","Veuillez lire ceci ! Pour utiliser Frost, vous devez d'abord sélectionner un sujet dans la fenêtre d'inforamtion des boards. Vous pouvez ouvrir cette fenêtre en cliquant sur le bouton 'i'.Vous pouvez envoyer des messages et des fichiers aux personnes qui utilisent la même board. Cela va sans doute prendre du temps avant que les premières boards n'apparaissent (cliquez sur le bouton 'mise à jour')."},
{"Please enter a name for the new board","Veuillez écrire un nom pour la nouvelle board"},
{"Please enter a name for the new folder","Veuillez écrire un nom pour le nouveau répertoire"},
{"Video","Vidéo"},
{"Video Extension","Extension fichiers vidéo"},
{"Show systray icon","Voir l'icone SysTray"},
{"Show board update visualization","Visualiser la mise à jour de la board"},
{"Show deleted messages","Voir les messages supprimés"},
{"Core.init.TransientNodeBody","Votre noeud est TRANSIENT. Un PERMANENT est meilleur pour freenet."},
{"Core.loadIdentities.InvalidNameBody","Votre pseudo ne doit pas contenir le caractère '@' !"},
{"Do you want to enter a subject?","Voulez-vous entrer un sujet ?"},
{"Do you really want to overwrite it?","Voulez-vous vraiment l'écraser ?"},
{"You already have a board with name","Vous avez déjà une board avec le nom"},
{"You must enter a sender name!","Vous devez écrire un nom d'expéditeur !"},
{"MoreSkinsAt","Vous pouvez obtenir plus de skins à"},
{"Wasting more time","Pure perte de temps"},
{"Windows Installer:","Installeur Windows :"},
{"MessageFrame.ConfirmBody1","Vous avez la clef privée de la board '"},
{"Email.body","Écrivez le corps de l'email. Le '<nom de fichier>' sera remplacé avec le nom du dossier"},
{"State","État"},
};
}
