/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class frost_ext_JSysTrayIcon */

#ifndef _Included_frost_ext_JSysTrayIcon
#define _Included_frost_ext_JSysTrayIcon
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: ERR_NO_ERROR */
/* Inaccessible static: ERR_INVALID_PARAM */
/* Inaccessible static: ERR_WINDOW_NOT_FOUND */
/* Inaccessible static: ERR_ICON_NOT_FOUND */
/* Inaccessible static: SHOW_CMD_HIDE */
/* Inaccessible static: SHOW_CMD_SHOW */
/* Inaccessible static: libLoaded */
/* Inaccessible static: iconList */
/* Inaccessible static: sysTrayIcon */
/*
 * Class:     frost_ext_JSysTrayIcon
 * Method:    nativeShowWindow
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_frost_ext_JSysTrayIcon_nativeShowWindow
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     frost_ext_JSysTrayIcon
 * Method:    nativeCreateSystrayIcon
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_frost_ext_JSysTrayIcon_nativeCreateSystrayIcon
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     frost_ext_JSysTrayIcon
 * Method:    nativeModifySystrayIcon
 * Signature: (IILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_frost_ext_JSysTrayIcon_nativeModifySystrayIcon
  (JNIEnv *, jobject, jint, jint, jstring, jstring);

/*
 * Class:     frost_ext_JSysTrayIcon
 * Method:    nativeDeleteSystrayIcon
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_frost_ext_JSysTrayIcon_nativeDeleteSystrayIcon
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
