/**
 * Language file for Frost
 *
 * This file has been created automatically.
 * Do NOT edit unless you REALLY know what you're doing!
 *
 * Language: fr
 */

package res;

import java.util.ListResourceBundle;

public class LangRes_fr extends ListResourceBundle {

public Object[][] getContents() {
    return contents;
}

static final Object[][] contents = {
{"About","A propos"},
{"Activate downloading","Activer le téléchargement"},
{"Add attachment(s)","Joindre"},
{"Add Board(s)","Joindre Board(s)"},
{"Add new board","Ajouter une board"},
{"Add new folder","Ajouter un repertoire"},
{"Add selected board","Ajouter la board"},
{"Age","Age"},
{"all boards","Toutes les boards"},
{"All files","Tous les fichiers"},
{"Allow 2 byte characters","Allow 2 byte characters"},
{"Archive Extension","Archive Extension"},
{"Archives","Archives"},
{"Audio","Audio"},
{"Audio Extension","Audio Extension"},
{"Automatic Indexing","Indexage Automatique"},
{"Automatic message update","Rafraichir automatiquement les messages"},
{"Automatic saving interval","Automatic saving interval"},
{"Automatic update options","Appliquer automatiquement les options"},
{"AvailableSkins","Skins Disponibles"},
{"batch explanation","bigger is faster but smaller is spam resistant"},
{"Block messages with body containing (separate by ';' )","Bloquer les messages contenants (separate by ';' )"},
{"Block messages with subject containing (separate by ';' )","Bloquer les messages ayant pour sujet (separate by ';' )"},
{"Block messages with these attached boards (separate by ';' )","Bloquer les messages ayant ces boards en piece jointe(separate by ';' )"},
{"block user (sets to BAD)","bloquer les utilisateurs  (noté BAD)"},
{"Blocks","Blocks"},
{"board","board"},
{"Board","Board"},
{"Board Information Window","Board Information Window"},
{"BoardInfoFrame.Board information window","Board information window"},
{"BoardInfoFrame.Boards","Boards"},
{"BoardInfoFrame.Close","Fermer"},
{"BoardInfoFrame.Files","Fichiers"},
{"BoardInfoFrame.Messages","Messages"},
{"BoardInfoFrame.Update","Rafraichir"},
{"BoardInfoFrame.Update all boards","Rafraichir toutes les boards"},
{"BoardInfoFrame.UpdateSelectedBoardButton","Rafraichir les Boards sélectionnées"},
{"BoardSettingsFrame.confirmBody","Si vous placez cette Board en public, vous perdrez ses clefs. Êtes-vous sûr de vouloir faire cela ?"},
{"BoardSettingsFrame.confirmTitle","Placez cette Board en public ? "},
{"BoardSettingsFrame.description","Description:"},
{"Bold","Gras"},
{"Bold Italic","Gras Italique"},
{"Browse","Passez en revue"},
{"Bulgarian","Bulgare"},
{"Cancel","Annuler"},
{"Change destination board","Change destination board"},
{"CHK key","Clef CHK"},
{"CHK key + filename","Clef CHK + nom du fichier"},
{"Choose","Choisir"},
{"Choose a Font","Choisir une police"},
{"Choose background color if updating board is not selected","Choisir la couleur de fond si rafraichir la board n'est pas choisi "},
{"Choose background color if updating board is selected","Choisir la couleur de fond si rafraichir la board est choisi"},
{"Choose boards to attach","Choisir les boards à joindre"},
{"Choose file(s) / directory(s) to attach","Sélectionnez le(s) fichier(s) / dossier(s) à joindre"},
{"Choose updating color of NON-SELECTED boards","Choisir la couleur utilisé pendant le rafraichissement des boards non-sélectionnées"},
{"Choose updating color of SELECTED boards","Choisir la couleur utilisé pendant le rafraichissement des boards sélectionnées"},
{"Clean the keypool","Clean the keypool"},
{"Configure board","Configurer la board"},
{"Configure selected board","Configurer le forum sélectionné"},
{"Copy to clipboard","Copier dans le presse papier"},
{"Core.init.NodeNotRunningBody","Assurez-vous que votre noeud fonctionne et que vous avez configuré freenet correctement."},
{"Core.init.NodeNotRunningTitle","Erreur - impossible d' établir une liaison à freenet."},
{"Core.init.TransientNodeBody","Votre noeud est TRANSIENT. Un PERMANENT est meuilleur pour freenet."},
{"Core.init.TransientNodeTitle","Noeud transient detecté"},
{"Core.loadIdentities.ChooseName","Choisissez un pseudo, il ne doit pas être obligatoirement unique "},
{"Core.loadIdentities.ConnectionNotEstablishedBody","Frost n'a pas pu établir une connection à freenet. Pour l' installation de Frost et créer votre pseudo une connection est nécessaire, apres vous pouvez lire les messages sans connection. Veuillez vous assurer que vous êtes connecté puis relancez Frost. "},
{"Core.loadIdentities.ConnectionNotEstablishedTitle","La connection a Freenet a échouée"},
{"Core.loadIdentities.InvalidNameBody","Votre pseudo ne doit pas contenir '@ '!"},
{"Core.loadIdentities.InvalidNameTitle","Pseudo invalide"},
{"Create message","Nouveau message"},
{"Cut","Couper"},
{"Cut board","Couper board"},
{"Date","Date"},
{"Decode each segment immediately after its download","Décoder chaque segment juste après son téléchargement"},
{"Decoding segment","Décoder segment"},
{"Decrease Font Size","Diminuez La Taille de Police"},
{"Default","Défaut "},
{"Description","Description"},
{"Destination","Destination"},
{"Disable all downloads","Stopper tous les téléchargements"},
{"Disable downloads","Stopper ce téléchargement"},
{"Disable selected downloads","Stopper les téléchargements sélectionnés"},
{"Disable splashscreen","Désactiver le splashscreen"},
{"Disable uploads","Désactiver les insertions"},
{"Display","Afficher"},
{"Display board information window","Afficher la fenetre d' infos des boards"},
{"Display known boards","Afficher les boards connues"},
{"Display list of known boards","Afficher la liste des boards connues"},
{"Do not trust","Ne pas faire confiance"},
{"Do spam detection","Do spam detection"},
{"Do you really want to overwrite it?","Voulez-vous vraiment l'écraser"},
{"Do you want to enter a subject?","Voulez-vous entrer un sujet?"},
{"Document Extension","Document Extension"},
{"Documents","Documents"},
{"Done","Terminé"},
{"Down","Down"},
{"Download all keys","Télécharger toutes les clefs"},
{"Download attachment(s)","Télécharger la(les) pièce(s) jointe(s)"},
{"Download directory","Répertoire de téléchargement"},
{"Download selected attachment","Télécharger la(les) pièce(s) jointe(s) sélectionnée(s)"},
{"Download selected keys","Télécharger les clefs sélectionnées"},
{"Downloads","Téléchargements"},
{"Dutch","Hollandais"},
{"Email.address","envoyez message à"},
{"Email.body","Écrivez le corps de l'email. Le \"<nom de fichier>\" sera remplacé avec le nom du dossier"},
{"Enable all downloads","Activer tous les téléchargements"},
{"Enable automatic board update","Activer le rafraichissement automatique des boards"},
{"Enable downloads","Activer téléchargements"},
{"Enable logging","Enable logging"},
{"Enable requesting of failed download files","Enable requesting of failed download files"},
{"Enable selected downloads","Activer tous les téléchargements sélectionnés"},
{"EnableMessageBodyAA","Activer l'anticrénelage pour le corps des messages"},
{"EnableSkins","Activer les Skins"},
{"Encode requested","Coder requested"},
{"Encoding file","Fichier en cours de codage"},
{"English","Anglais"},
{"Executable Extension","Executable Extension"},
{"Executables","Executables"},
{"Exit","Quitter"},
{"Experimental Freenet Browser","Browser Expérimental de Freenet"},
{"Failed","Echoué"},
{"File","Fichier"},
{"File List","Liste de fichier"},
{"Filename","Nom du fichier"},
{"Files","Fichiers"},
{"Folder","Repertoire"},
{"folder","repertoire"},
{"Fonts","Polices"},
{"French","Francais"},
{"From","Auteur"},
{"Frost by Jantho","Frost par RapHHfr"},
{"FrostSearchItemObject.Anonymous","Anonyme"},
{"FrostSearchItemObject.Offline","En différé"},
{"Generate new keypair","Générer une nouvelle paire de clefs"},
{"German","Allemand"},
{"Help","Aide"},
{"Help spread files from people marked GOOD","Help spread files from people marked GOOD"},
{"help user (sets to GOOD)","Aider les utilisateurs (noté GOOD)"},
{"Hide files from anonymous users","Cacher les fichiers des utilisateurs anonymes"},
{"Hide files from people marked BAD","Cacher les fichiers des utilisateurs BAD"},
{"Hide messages flagged BAD","Cacher les messages marqué BAD"},
{"Hide messages flagged CHECK","Cacher les messages marqué CHECK"},
{"Hide messages flagged N/A","Cacher les messages marqué N/A"},
{"Hide unsigned messages","Cacher les messages non signés"},
{"High","Haut"},
{"hours","heures"},
{"Hypercube fluctuating!","Hypercube fluctuating!"},
{"Image Extension","Image Extension"},
{"Images","Images"},
{"Increase Font Size","Augmentez La Taille de Police"},
{"Index","Index"},
{"Index file redundancy","Index des fichiers Redondants"},
{"Indexed attachments","Indexed attachments"},
{"Initializing Mainframe","Unité centrale d'Initialisation"},
{"Invert enabled state for all downloads","Inversez l'état pour tous les téléchargements"},
{"Invert enabled state for selected downloads","Inversez l'état permis pour les téléchargements sélectionnés"},
{"Italian","Italien"},
{"Italic","Italique"},
{"Japanese","Japonais"},
{"Key","Clef"},
{"Keyfile download HTL","HTL de Téléchargement."},
{"Keyfile upload HTL","HTL d'insertion"},
{"KnownBoardsFrame.Add board","Ajouter board"},
{"KnownBoardsFrame.Close","Fermer"},
{"KnownBoardsFrame.List of known boards","Liste des boards connus"},
{"KnownBoardsFrame.Lookup","Consulter"},
{"KnownBoardsFrame.Remove board","Supprimer board"},
{"KnownBoardsTableModel.Boardname","Nom de la Board"},
{"Language","Langue"},
{"Last upload","Dernier envoi"},
{"list of nodes","Comma-separated list of nodes you have FCP access to"},
{"list of nodes 2","(nodeA:portA, nodeB:portB, ...)"},
{"Log file size limit (in KB)","Log files size limit  (in KB)"},
{"Logging level","Logging level"},
{"Low","Bas"},
{"Mark ALL messages read","Marquer TOUS LES messages lus"},
{"Mark message unread","Marquer  message non-lu"},
{"Maximum message display (days)","Affichage des messages maximum (En jours)"},
{"Maximum number of keys to store","Nombre maximum des clefs stockées"},
{"Maximum number of retries","Nombre maximum de nouvelles tentatives"},
{"Maximum search results","Résultats maximum de recherche"},
{"Medium","Milieu"},
{"Message base","Base de message"},
{"Message Body","Corps de message"},
{"Message download HTL","HTL de Téléchargement des messages"},
{"Message List","Liste de Message"},
{"Message upload HTL","HTL d' insertion des messages"},
{"MessageBodyFont","Police de Corps de message"},
{"Messages","Messages"},
{"Messages Today","Messages d'Aujourd'hui"},
{"Minimize to System Tray","Réduire dans le System Tray"},
{"Minimum update interval of a board","Intervalle minimum de mise à jour d'une board"},
{"minutes","minutes"},
{"Miscellaneous","Divers"},
{"MoreSkinsAt","Vous pouvez obtenir plus de skins à"},
{"Never","Jamais"},
{"New board","Nouvelle board"},
{"New folder","Nouveau repertoire"},
{"New Folder Name","Nouveau nom de repertoire"},
{"New message","Nouveau message"},
{"New Node Name","Nouveau nom de Board"},
{"newboard","Nouvelle Board"},
{"NewBoardDialog.add","Ajouter Board"},
{"NewBoardDialog.description","Description (Facultative). Ne mettez pas d'information privée ici :"},
{"NewBoardDialog.details","Veuillez entrer les détails de la nouvelle board:"},
{"NewBoardDialog.name","Nom:"},
{"NewBoardDialog.title","Ajouter une nouvelle board"},
{"newfolder","Nouveau repertoire"},
{"News","Forums"},
{"No","Non"},
{"No 'From' specified!","Aucun  'From' est indiqué ! "},
{"No subject specified!","Aucun sujet spécifié!"},
{"NoSkinsFound","Aucune Skins trouvée"},
{"Not available","Indisponible"},
{"Number of concurrently updating boards","Number of concurrently updating boards"},
{"Number of days to display","Nombre de jours d'affichage"},
{"Number of days to download backwards","Number of days to download backwards"},
{"Number of simultaneous downloads","Nombre de téléchargements simultanés"},
{"Number of simultaneous uploads","Nombre d'insertions simultanés"},
{"Number of splitfile threads","Nombre de splitfile threads"},
{"Off","Off"},
{"OK","Ok"},
{"On","On"},
{"Open Source Project (GPL license)","Open Source Project (GPL license)"},
{"Options","Options"},
{"Override default settings","Override default settings"},
{"Paste","Coller"},
{"Paste board","Coller board"},
{"Path","Chemin"},
{"Pause downloading","Téléchargement en pause"},
{"Plain","plaine"},
{"Please choose a new name","Veuillez choisir un nouveau nom"},
{"Please enter a name for the new board","Veuillez écrire un nom pour la nouvelle board"},
{"Please enter a name for the new folder","Veuillez écrire un nom pour le nouveau répertoire"},
{"Please enter the prefix you want to use for your files.","Veuillez entrer le préfixe que vous voulez utiliser pour vos fichiers:"},
{"Plugins","Plugins"},
{"Preferences","Préférences"},
{"Preview","Preview"},
{"Private key","Clef privée"},
{"Public board","Forum publique"},
{"Public key","Clef publique"},
{"Reaching ridiculous speed...","Reaching ridiculous speed..."},
{"redundancy explanation","ne travaille pas encore"},
{"Refresh","Rafraichir"},
{"RefreshList","Rafraichir Liste"},
{"Reload all files","Recharger tous les fichiers"},
{"Reload selected files","Recharger les fichiers sélectionnés"},
{"Remove","supprimer"},
{"Remove all downloads","Effacer tous les téléchargements"},
{"Remove all files","Effacer tous les fichiers"},
{"Remove board","Supprimer board"},
{"Remove finished downloads","Supprimer les téléchargements finis"},
{"Remove finished downloads every 5 minutes","Supprimer les téléchargements finis toutes les 5 minutes "},
{"Remove selected downloads","Effacer les téléchargements sélectionnés"},
{"Remove selected files","Effacer les fichiers sélectionnés"},
{"Rename folder","Renommer repertoire"},
{"Reply","Répondre"},
{"Request file after this count of retries","Request file after this count of retries"},
{"Requested","Requested"},
{"Requesting","Requesting"},
{"Restart failed downloads","Relancer les téléchargements loupés"},
{"Restart selected downloads","Relancer les téléchargements selectionnés"},
{"Restore default filenames for all files","Restaurer les noms de fichiers par défaut de tous les fichiers"},
{"Restore default filenames for selected files","Restaurer les noms de fichiers par défaut des fichiers sélectionnés"},
{"Results","Resultats"},
{"Sample","Sample"},
{"Sample interval","Sample interval"},
{"Save message","Sauvegarder le message"},
{"Save message to disk","Enregistrer ce message sur le disque..."},
{"Search","Recherche"},
{"SearchTableFormat.Downloaded","Téléchargé"},
{"SearchTableFormat.Downloading","Téléchargement "},
{"SearchTableFormat.Uploading","Uploading"},
{"Secure board","Forum sécurisé"},
{"Select a board to view its content.","Choisissez une board pour voir son contenu"},
{"Select a message to view its content.","Sélectionnez un message pour voir son contenu."},
{"Select download directory","Choisir le repertoire de téléchargement"},
{"Select files you want to upload to the","Choisir les fichiers à upload"},
{"Selected board","Board selectionné"},
{"Send message","Envoyer le message"},
{"Sending IP address to NSA","Vérification de connection à Freenet"},
{"Set prefix for all files","Définir le préfixe de tous les fichiers"},
{"Set prefix for selected files","Définir le préfixe des fichiers sélectionnés"},
{"Set to","Set to"},
{"Set to CHECK","Set to CHECK"},
{"set to neutral (CHECK)","set to neutral (CHECK)"},
{"Settings for board","Option de la board"},
{"Share Downloads","Partager les Téléchargements"},
{"Should file attachments be added to upload table?","Should file attachments be added to upload table?"},
{"Show board update visualization","Voir la mise à jour de la board"},
{"Show healing information","Show healing information"},
{"Show systray icon","Voir l'icone SysTray"},
{"Sig","Sig"},
{"Sign","Signer"},
{"Sign shared files","Signer les fichiers partagés"},
{"Signature","Signature"},
{"Size","Taille"},
{"SMTP.password","mot de passe"},
{"SMTP.server","server address"},
{"SMTP.username","pseudo"},
{"Sort folder","Classer les répertoires"},
{"Source","Source"},
{"Spanish","Espagnol"},
{"splitfile explanation","(plus grand est plus rapide mais utilise plus de CPU)"},
{"Start encoding of selected files","Commencez le codage des fichiers choisis"},
{"State","État"},
{"Status","Statut"},
{"Subject","Sujet"},
{"This will not delete messages","Ceci ne supprimera pas de messages"},
{"Threshold of blocked messages","Seuil des messages bloqués "},
{"TOFDO","TOFDO"},
{"TOFUP","TOFUP"},
{"Translate Frost into another language","Traduire Frost en une autre langue"},
{"Tries","Tries"},
{"Trust","Trust"},
{"Try to download all segments, even if one fails","Essayez de télécharger tous les segments, même si un échoue"},
{"Trying","Essai en cours"},
{"Unknown","Inconnu"},
{"Up","Up"},
{"up htl explanation","(bigger is slower but more reliable)"},
{"Update","Mettre à jour"},
{"Upload all files","Uploader tous les fichiers"},
{"Upload batch size","Upload batch size"},
{"Upload HTL","Upload HTL"},
{"Upload selected files","Uploader les fichiers selectionnés"},
{"Uploading","Envoi en cours"},
{"Uploads","Envois"},
{"UploadsUnderway.body","Quelques messages sont toujours en envois. Voulez-vous vraiment quitter ?"},
{"UploadsUnderway.title","Uploads en cours"},
{"Use default","Use default"},
{"Use editor for writing messages","Use editor for writing messages"},
{"Version","Version"},
{"Very high","Très haut"},
{"Very low","Très bas"},
{"Video","Video"},
{"Video Extension","Video Extension"},
{"Waiting","En attente"},
{"Waittime after each try","Temps d'attente après chaque essai"},
{"Warning","Avertissement"},
{"Wasting more time","Wasting more time"},
{"Welcome message","Veuillez lire ceci !  To use Frost, you first need to select a topic from the board information window. You can openthis window with the i-button above. You can send messages and files to people using the same board. It will probably take some time until the first boards show up (press the update button)."},
{"Yes","Oui"},
{"You already have a board with name","Vous avez déjà une board avec ce nom"},
{"You must enter a sender name!","Vous devez écrire un nom d'expéditeur ! "},
{"You must enter a subject!","You must enter a subject!"},
};
}
