/**
 * Language file for Frost
 *
 * This file has been created automatically.
 * Do NOT edit unless you REALLY know what you're doing!
 *
 * Language: de
 */

package res;

import java.util.ListResourceBundle;

public class LangRes_de extends ListResourceBundle {

public Object[][] getContents() {
    return contents;
}

static final Object[][] contents = {
{"Requested","Angefragt"},
{"Remove selected files","Gewählte Dateien entfernen"},
{"Waittime after each try","Wartezeit nach jedem Versuch"},
{"Help","Hilfe"},
{"Send message","Nachricht senden"},
{"Should file attachments be added to upload table?","Attachments in die Uploadliste eintragen?"},
{"Hide unsigned messages","Unsignierte Nachrichten verstecken"},
{"Public key","Öffentlicher Schlüssel"},
{"splitfile explanation","(mehr ist besser, brauch aber auch Leistung)"},
{"Remove finished downloads every 5 minutes","Fertige Downloads alle 5 Minuten entfernen"},
{"Waiting","Warte"},
{"New folder","Neuer Ordner"},
{"Do spam detection","Spam Erkennung"},
{"Disable downloads","Downloads deaktivieren"},
{"Help spread files from people marked GOOD","Leute die als 'GOOD' markiert sind untertützen"},
{"Add new folder","Neuen Ordner hinzufügen"},
{"No 'From' specified!","Absender fehlt!"},
{"Index","Index"},
{"Add Board(s)","Foren hinzufügen"},
{"Automatic Indexing","Automatischer Index"},
{"Search","Suchen"},
{"RefreshList","Liste aktualisieren"},
{"Download selected attachment","Download selected attachment"},
{"Download selected keys","Gewählte Schlüssel runterladen"},
{"Mark message unread","Gewählte Nachrichten als ungelesen markieren"},
{"New board","Neues Forum"},
{"Try to download all segments, even if one fails","Versuche alle Segmente runterzuladen, auch wenn eines fehlschlägt"},
{"Upload selected files","Gewählte Dateien hochladen"},
{"Enable downloads","Downloads aktivieren"},
{"Restart selected downloads","Gewählte Downloads starten"},
{"CHK key","CHK Schlüssel"},
{"Files","Dateien"},
{"Remove","Entferne"},
{"Select files you want to upload to the","Dateien wählen, die hinzugefügt werden sollen zum"},
{"Folder","Folder"},
{"all boards","Alle Foren"},
{"Status","Status"},
{"Preview","Vorschau"},
{"Maximum number of retries","Maximale Zahl an Einträgen"},
{"Upload all files","Alle Dateien hochladen"},
{"Welcome message","LESEN!\n\nNa toll, jetzt hab ich den Text vergessen."},
{"KnownBoardsFrame.Close","Schließen"},
{"German","Deutsch"},
{"Filename","Dateiname"},
{"Disable splashscreen","Splashscreen abschalten"},
{"OK","OK"},
{"Enable all downloads","Alle Downloads aktivieren"},
{"Download all keys","Alle Schlüssel runterladen"},
{"MoreSkinsAt","Mehr Skins gibt's hier"},
{"AvailableSkins","Vorhandene Skins"},
{"Italian","Italienisch"},
{"Maximum search results","Anzahl der Suchresultate"},
{"Start encoding of selected files","Gewählte Dateien kodieren"},
{"Number of simultaneous downloads","Gleichzeitige Downloads"},
{"Save message to disk","Nachricht speichern"},
{"Disable selected downloads","Gewählte Downloads deaktivieren"},
{"Bulgarian","Bulgarian"},
{"up htl explanation","(größer ist zuverlässiger aber langsamer)"},
{"Generate new keypair","Neues Schlüsselpaar generieren"},
{"Hide files from anonymous users","Dateien vor anonymen Nutzern verstecken"},
{"Uploads","Hochladen"},
{"Remove board","Forum entfernen"},
{"Enable selected downloads","Gewählte Downloads aktivieren"},
{"Executable Extension","Executable Extension"},
{"Restore default filenames for selected files","Standarddateinamen für gewählte Dateien wiederherstellen"},
{"Threshold of blocked messages","Grenzwert für blockierte Nachrichten"},
{"Add selected board","Gewähltes Forum hinzufügen"},
{"Translate Frost into another language","Frost übersetzen"},
{"Secure board","Sicheres Forum"},
{"Upload batch size","Upload Batch Größe"},
{"Increase Font Size","Größere Schrift"},
{"Sign","Signieren"},
{"Update","Aktualisieren"},
{"You must enter a subject!","Titel angeben!"},
{"BoardInfoFrame.Update","Aktualisieren"},
{"Trust","Vertrauen"},
{"Number of days to download backwards","Zurückliegende Tage, die gelesen werden sollen"},
{"Cut board","Forum ausschneiden"},
{"KnownBoardsFrame.List of known boards","Liste bekannter Foren"},
{"Choose background color if updating board is not selected","Hintergrundfarbe für nichtgewählte Foren, die aktualisiert werden"},
{"board","Forum"},
{"Plugins","Plugins"},
{"Age","Alter"},
{"Hide messages flagged N/A","Mit N/A markierte Nachrichten verbergen"},
{"No subject specified!","Kein Titel!"},
{"Size","Größe"},
{"Number of splitfile threads","Splitfile Threads"},
{"Invert enabled state for all downloads","Enable Status für alle Downloads invertieren"},
{"News","Nachrichten"},
{"NoSkinsFound","Keine Skins gefunden"},
{"Invert enabled state for selected downloads","Enable Status für gewählte Downloads invertieren"},
{"Number of days to display","Anzahl dargestellter Tage"},
{"Message upload HTL","Nachrichtenupload HTL"},
{"BoardInfoFrame.Boards","Foren"},
{"Restart failed downloads","Fehlgeschlagene Downloads wiederholen"},
{"Mark ALL messages read","Alle Nachrichten als gelesen markieren"},
{"Done","Erledigt"},
{"Do not trust","Nicht vertrauen"},
{"list of nodes","Komma getrennte Liste von FCP Knoten"},
{"About","Über"},
{"Private key","Privater Schlüssel"},
{"Board Information Window","Forumsinformationen"},
{"KnownBoardsFrame.Lookup","Suchen"},
{"Image Extension","Image Extension"},
{"Block messages with body containing (separate by ';' )","Blockiere Nachrichtentexte mit (trenne mit ';' )"},
{"Restore default filenames for all files","Standarddateinamen wiederherstellen"},
{"Show healing information","Heilungsinfos anzeigen"},
{"Choose updating color of SELECTED boards","Aktualisierungsfarbe für gewählte Foren"},
{"BoardInfoFrame.UpdateSelectedBoardButton","Gewähltes Forum aktualisieren"},
{"Message base","Nachrichtenbasis"},
{"Messages","Nachrichten"},
{"minutes","Minuten"},
{"Clean the keypool","Keypool leeren"},
{"BoardInfoFrame.Update all boards","Alle Foren aktualisieren"},
{"Add new board","Neues Forum hinzufügen"},
{"Key","Schlüssel"},
{"Trying","Anfrage"},
{"Sample interval","Sample interval"},
{"Date","Datum"},
{"Options","Optionen"},
{"block user (sets to BAD)","Nutzer blockieren (auf BAD setzen)"},
{"Index file redundancy","Indexdatei Redundanz"},
{"Display known boards","Bekannte Foren anzeigen"},
{"Signature","Signatur"},
{"You must enter a sender name!","Absender eingeben!"},
{"Upload HTL","Hochlade HTL"},
{"Enable requesting of failed download files","Fehlgeschlagene Downloads anfordern"},
{"Board","Forum"},
{"Minimum update interval of a board","Minimales Updateinterval eines Forums"},
{"Audio Extension","Audio Extension"},
{"Share Downloads","Downloads teilen"},
{"On","An"},
{"Miscellaneous","Verschiedenes"},
{"Cancel","Abbruch"},
{"Uploading","Aktiv"},
{"Destination","Ziel"},
{"State","Status"},
{"BoardInfoFrame.Files","Dateien"},
{"Never","Nie"},
{"Keyfile download HTL","Keyfile Download HTL"},
{"Show systray icon","Taskleistenicon anzeigen"},
{"Results","Ergebnisse"},
{"BoardInfoFrame.Messages","Nachrichten"},
{"English","Englisch"},
{"KnownBoardsFrame.Add board","Forum hinzufügen"},
{"TOFDO","TOFDO"},
{"Path","Pfad"},
{"Please enter the prefix you want to use for your files.","Dateipräfix"},
{"Do you want to enter a subject?","Wollen sie einen Titel eingeben?"},
{"Disable uploads","Uploads deaktivieren"},
{"Select download directory","Select download directory"},
{"Save message","Nachricht sichern"},
{"Download directory","Downloadverzeichnis"},
{"Exit","Ende"},
{"Browse","Durchsuchen"},
{"Remove finished downloads","Fertige Downloads aus Liste entfernen"},
{"Copy to clipboard","Ins Clipboard kopieren"},
{"Last upload","Letzter Upload"},
{"Reply","Antworten"},
{"Document Extension","Document Extension"},
{"hours","Stunden"},
{"Spanish","Spanisch"},
{"Keyfile upload HTL","Keyfile Upload HTL"},
{"Maximum number of keys to store","Anzahl gespeicherter Schlüssel"},
{"redundancy explanation","geht net"},
{"Download attachment(s)","Attachments runterladen"},
{"New message","Neue Nachricht"},
{"Add attachment(s)","Attachments anhängen"},
{"Messages Today","Heutige Nachrichten"},
{"Block messages with subject containing (separate by ';' )","Blockiere Nachrichten die im Titel enthalten (trenne mit ';' )"},
{"Unknown","Unbekannt"},
{"Use editor for writing messages","Editor zum Verfassen von Nachrichten verwenden"},
{"File","Datei"},
{"MessageBodyFont","Zeichensatz für Nachricht"},
{"TOFUP","TOFUP"},
{"Display list of known boards","Liste bekannter Foren"},
{"Reload all files","Alle Dateien hochladen"},
{"Paste","Paste"},
{"Off","Aus"},
{"Set prefix for all files","Präfix für alle Dateien setzen"},
{"Activate downloading","Downloads aktivieren"},
{"Rename folder","Ordner umbenennen"},
{"BoardInfoFrame.Close","Schließen"},
{"Choose updating color of NON-SELECTED boards","Updatefarbe für nicht selektierte Foren"},
{"help user (sets to GOOD)","Nutzer unterstützen (auf 'GOOD' setzen)"},
{"Experimental Freenet Browser","Experimentalbrowser für Freenet (naja...)"},
{"French","Französisch"},
{"Automatic update options","Einstellungen für Automatische Updates"},
{"Frost by Jantho","Frost von Jantho"},
{"Public board","Öffentliches Forum"},
{"Remove all downloads","Alle Downloads entfernen"},
{"Preferences","Einstellungen"},
{"Down","Ab"},
{"New Node Name","Neuer Forumsname"},
{"Request file after this count of retries","Datei nach folgender Anzahl von Versuchen anfordern"},
{"Archive Extension","Archive Extension"},
{"Indexed attachments","Indexed Attachments"},
{"Subject","Betreff"},
{"Select a message to view its content.","Nachricht auswählen um Inhalt zu sehen"},
{"Automatic message update","Automatische Forumsupdate"},
{"Failed","Fehler"},
{"Choose background color if updating board is selected","Hintergrundfarbe falls selektiertes Forum aktualisiert wird"},
{"Selected board","Gewähltes Forum"},
{"Configure selected board","Gewähltes Forum konfigurieren"},
{"Remove selected downloads","Gewählte Downloads entfernen"},
{"Display board information window","Forumsinformationen"},
{"Show board update visualization","Aktualisierungsinformationen"},
{"Dutch","Holländisch"},
{"Decode each segment immediately after its download","Segmente sofort nach dem Download dekodieren"},
{"Disable all downloads","Alle Downloads deaktivieren"},
{"Set prefix for selected files","Präfix für selektierte Dateien"},
{"Display","Anzeige"},
{"Sign shared files","Angebotene Dateien signieren"},
{"Japanese","Japanisch"},
{"Create message","Erstelle Nachricht"},
{"folder","folder"},
{"Choose boards to attach","Forum für Anhang auswählen"},
{"Language","Sprache"},
{"Hide files from people marked BAD","Dateien vor mit 'BAD' markierten Leuten verbergen"},
{"Paste board","Forum einfügen"},
{"Minimize to System Tray","In die Taskleiste minimieren"},
{"KnownBoardsFrame.Remove board","Forum entfernen"},
{"batch explanation","Größer ist schneller, kleiner ist Spamsicherer"},
{"Number of concurrently updating boards","Gleichzeitig aktualisierte Foren"},
{"Video Extension","Video Extension"},
{"Hide messages flagged BAD","Mit 'BAD' markierte Nachrichten verbergen"},
{"Message download HTL","Nachrichten Download HTL"},
{"BoardInfoFrame.Board information window","Forumsinformationen"},
{"Cut","Entferne"},
{"From","Von"},
{"Choose file(s) / directory(s) to attach","Dateien/Verzeichnisse als Attachments auswählen"},
{"Hide messages flagged CHECK","Verberge mit 'CHECK' markierte Nachrichten"},
{"Up","Auf"},
{"Downloads","Herunterladen"},
{"Change destination board","Zielforum ändern"},
{"Configure board","Forum konfigurieren"},
{"Decrease Font Size","Kleinere Schrift"},
{"Source","Quelle"},
{"CHK key + filename","CHK Schlüssel + Dateiname"},
{"EnableSkins","Skins aktivieren"},
{"Number of simultaneous uploads","Gleichzeitige Uploads"},
{"Allow 2 byte characters","2Byte Zeichen (habe wir doch jetzt sowieso...)"},
{"Reload selected files","Gewählte Dateien hochladen"},
{"Automatic saving interval","Automatische Speicherintervall"},
{"Remove all files","Alle Dateien entfernen"},
{"Not available","Nicht vorhanden"},
{"Refresh","Aktualisiere"},
{"Set to CHECK","Mit 'CHECK' markieren"},
};
}
