/**
 * Language file for Frost
 *
 * This file has been created automatically.
 * Do NOT edit unless you REALLY know what you're doing!
 *
 * Language: bg
 */

package res;

import java.util.ListResourceBundle;

public class LangRes_bg extends ListResourceBundle {

public Object[][] getContents() {
    return contents;
}

static final Object[][] contents = {
{"Requested","Поръчан"},
{"Remove selected files","Премахни избраните файли"},
{"Help","Помощ"},
{"Waittime after each try","Интервал между опитите"},
{"Send message","Изпрати"},
{"Should file attachments be added to upload table?","Добавя прикачените файлове в списъка на качванията"},
{"Hide unsigned messages","Филтрирай неподписани съобщения"},
{"Public key","публичен ключ"},
{"Remove finished downloads every 5 minutes","Премахване на приключили сваляния всеки пет минути"},
{"splitfile explanation","(Повече е по-бързо но иска повече CPU)"},
{"Waiting","Чакане"},
{"New folder","НоваПапка"},
{"Do spam detection","Засичане на спам"},
{"Disable downloads","Забрани сваляния"},
{"Help spread files from people marked GOOD","Помагане на файлове на контакти маркирани GOOD"},
{"Add new folder","Добави нова папка"},
{"No 'From' specified!","Не е даден подател!"},
{"Index","Индекс"},
{"Refresh folder","Обнови папка"},
{"Add Board(s)","Добави борд"},
{"Automatic Indexing","Автоматично индексиране"},
{"Search","Търси"},
{"RefreshList","Обнови списък"},
{"Download selected keys","Свали избраните файли"},
{"New board","Нов борд"},
{"Mark message unread","Маркирай като непрочетено"},
{"Restart selected downloads","Рестартирай израните сваляния"},
{"Enable downloads","Включване на свалянията"},
{"Upload selected files","Качи избраните файли"},
{"Try to download all segments, even if one fails","Всички сегменти да бъдат свалени, дори един да не успее"},
{"CHK key","CHK ключ"},
{"Files","Файли"},
{"Remove","Изтрий"},
{"all boards","всички бордове"},
{"Status","Статус"},
{"Preview","Преглед"},
{"Maximum number of retries","Максимален брой опити"},
{"Upload all files","Качи всички файли"},
{"Welcome message","Please read this!\n\nTo use Frost, you first need to select a topic from the board information window. You can openthis window with the i-button above. You can send messages and files to people using the same board. It will probably take some time until the first boards show up (press the update button)."},
{"German","German"},
{"Filename","Име на файл"},
{"Disable splashscreen","Премахни началния екран"},
{"OK","OK"},
{"Enable all downloads","Включи всички сваляния"},
{"Download all keys","Свали всички резултати"},
{"MoreSkinsAt","Можете да намерите още скинове на адрес"},
{"AvailableSkins","Инсталирани скинове"},
{"Italian","Italian"},
{"Maximum search results","Максимален брой резултати"},
{"Start encoding of selected files","Започни кодиране на избраните файли"},
{"Number of simultaneous downloads","Брой едновременни сваляния"},
{"Save message to disk","Запиши съобщението на диск"},
{"Disable selected downloads","Спри избраните сваляния"},
{"Bulgarian","Български"},
{"up htl explanation","(повече е по-бавно но по-сигурно)"},
{"Generate new keypair","Генерирай нов чифт ключове"},
{"Hide files from anonymous users","Не показвай неподписани файлове"},
{"Uploads","Качвания"},
{"Remove board","Премахни борд"},
{"Enable selected downloads","Включи избраните сваляния"},
{"Executable Extension","Разширение на изпълними файли"},
{"Restore default filenames for selected files","Възтанови оригиналните имена на избраните файли"},
{"Threshold of blocked messages","Брой блокирани съобщения"},
{"Translate Frost into another language","Преведи фрост на друг език"},
{"Add selected board","Добави избраният борд"},
{"Secure board","Защитен борд"},
{"Increase Font Size","Увеличи размера на фонта"},
{"Upload batch size","Намали размера на фонта"},
{"Sign","Подпиши"},
{"Update","Обнови"},
{"You must enter a subject!","You must enter a subject!"},
{"Trust","Доверие"},
{"Number of days to download backwards","Колко дни назад да се обновяват"},
{"Cut board","Отрежи борд"},
{"Choose background color if updating board is not selected","Фонов цвят ако обновяваният борд не е избран"},
{"Age","Възраст"},
{"Plugins","Модули"},
{"board","борд"},
{"Hide messages flagged N/A","Hide messages flagged N/A"},
{"No subject specified!","No subject specified!"},
{"Size","Размер"},
{"Number of splitfile threads","Брой тредове"},
{"News","Съобщения"},
{"Invert enabled state for all downloads","Инвертирай вкл/изкл. на всички сваляния"},
{"NoSkinsFound","Не са намерини скинове!"},
{"Invert enabled state for selected downloads","Инвертирай вкл/изкл на избраните сваляния!"},
{"Number of days to display","Колко дни да се показват"},
{"Message upload HTL","HTL за качване на съобщения"},
{"Restart failed downloads","Рестартиране на неуспешни сваляния"},
{"Mark ALL messages read","Маркирай всички съобщения като прочетени"},
{"Done","Готов"},
{"Do not trust","Недоверие"},
{"list of nodes","Списък на Фрийнет възели до които имате достъп (разделен със запетая)"},
{"About","Относно"},
{"Private key","Частен ключ"},
{"Board Information Window","Информация за бордовете"},
{"Image Extension","Разширение за графични файли"},
{"Restore default filenames for all files","Възтанови оригиналните имена на всички файли"},
{"Block messages with body containing (separate by ';' )","Блокирай съобщения които съдържат"},
{"Show healing information","Покажи възтановителна информация"},
{"Choose updating color of SELECTED boards","Избери цвят за обновяващи се бордове"},
{"BoardInfoFrame.UpdateSelectedBoardButton","Обнови избраният борд"},
{"Message base","База на съобщенията"},
{"Messages","Съобщения"},
{"minutes","минути"},
{"Clean the keypool","почистване на keypool-a"},
{"Add new board","Добави нов борд"},
{"Key","Ключ"},
{"Trying","Опитвам се..."},
{"Sample interval","Интервал на семплиране"},
{"Date","Дата"},
{"Options","Настройки"},
{"block user (sets to BAD)","блокирай потребител (маркира BAD)"},
{"Display known boards","Списък на известните бордове"},
{"Index file redundancy","Index file redundancy"},
{"Signature","Подпис"},
{"You must enter a sender name!","Трябва да дадете име на подател!"},
{"Board","Борд"},
{"Enable requesting of failed download files","Включи поръчване на неуспешни сваляния"},
{"Upload HTL","HTL на качване"},
{"Minimum update interval of a board","Минимален интервал на обновяване на бордове"},
{"Audio Extension","Разширение на изпълними файли"},
{"On","Вкл."},
{"Share Downloads","Индексиране на свалените файли"},
{"Miscellaneous","Разни"},
{"Uploading","Качване"},
{"Cancel","Отказ"},
{"State","Състояние"},
{"Destination","Борд"},
{"Never","Никога"},
{"Keyfile download HTL","HTL за сваляне на индекс файл"},
{"Show systray icon","покажи икона в систрай-а"},
{"Results","Резултати"},
{"Board information","Информация за борда"},
{"English","English"},
{"Path","път"},
{"TOFDO","TOFDO"},
{"Please enter the prefix you want to use for your files.","Дайте префиксът за вашите файли"},
{"Do you want to enter a subject?","Искате ли да дадете заглавие?"},
{"Disable uploads","Изкючи качванията"},
{"Save message","Запиши съобщението"},
{"Exit","Изход"},
{"Download directory","Директория за сваляне"},
{"Remove finished downloads","Премахни приключилите сваляния"},
{"Browse","Търси.."},
{"Last upload","Последно качване"},
{"Copy to clipboard","Копирай в клипборда"},
{"Reply","Отговори"},
{"Document Extension","Разширение за документи"},
{"Spanish","Spanish"},
{"hours","часове"},
{"Keyfile upload HTL","HTL за качване на индекс файл"},
{"Maximum number of keys to store","Максимален брой ключове в keypool-a"},
{"redundancy explanation","not working yet"},
{"Download attachment(s)","Свали прикачените файли"},
{"New message","Ново съобщение"},
{"Add attachment(s)","Прикачи файли"},
{"Messages Today","Съобщения днес"},
{"Block messages with subject containing (separate by ';' )","Блокирай съобщения чието заглавие съдържа "},
{"Unknown","Неизвестен"},
{"Use editor for writing messages","Use editor for writing messages"},
{"File","Файл"},
{"MessageBodyFont","Фонт на тялото на съобщението"},
{"Display list of known boards","Покажи списък на известните бордове"},
{"TOFUP","TOFUP"},
{"Reload all files","Качи всички файли"},
{"Set prefix for all files","Добави префикс на всички файли"},
{"Off","Изкл."},
{"Rename folder","Преименувай папка"},
{"Activate downloading","включи свалянето"},
{"help user (sets to GOOD)","помогни на потребителя (маркира GOOD)"},
{"Choose updating color of NON-SELECTED boards","Избери цвят на бордове които се обновяват и не са избрани"},
{"Experimental Freenet Browser","Експериментален Freenet Browser"},
{"French","French"},
{"Automatic update options","Настройки на автоматичното обновяване"},
{"Frost by Jantho","Frost by Jantho"},
{"Public board","Публичен борд"},
{"Preferences","Настройки"},
{"Remove all downloads","Премахни всички сваляния"},
{"Down","Долу"},
{"New Node Name","Име на новия борд"},
{"Request file after this count of retries","Поръчай файла след # опити"},
{"Archive Extension","разширение на архивни файли"},
{"Indexed attachments","индексирай прикачените файлове"},
{"Subject","Заглавие"},
{"Select a message to view its content.","Изберете съобщение за да видите съдържанието му."},
{"Automatic message update","Автоматично обновяване на бордовете"},
{"Failed","Неуспешен"},
{"Selected board","Избран борд"},
{"Choose background color if updating board is selected","Изберете фонов цвят ако избраният борд се обновява"},
{"Configure selected board","Конфигурирайте избраният борд"},
{"Remove selected downloads","Премахни избраните сваляния"},
{"Display board information window","Покажи информация за бордовете"},
{"Dutch","Dutch"},
{"Show board update visualization","Визуализация на обновяването"},
{"Decode each segment immediately after its download","Декодирай всеки сегмент веднага щом бъде свален"},
{"Disable all downloads","Изключи всички сваляния"},
{"Set prefix for selected files","Добави префикс на избраните файли"},
{"Display","Скинове"},
{"Sign shared files","Подписване на индексираните файли"},
{"Japanese","Japanese"},
{"Create message","Създай съобщение"},
{"Language","Language"},
{"Choose boards to attach","Избери бордове за прикачване"},
{"Hide files from people marked BAD","Блокирай файлове от контакти маркирани BAD"},
{"Boards","Бордове"},
{"Paste board","Paste board"},
{"Minimize to System Tray","Minimize to System Tray"},
{"batch explanation","по-голям е по-бърз но по-малък е по-спамоусойчив"},
{"Number of concurrently updating boards","Брой на бордове които се обновяват едновременно "},
{"Video Extension","Разширение на видео файли"},
{"Message download HTL","HTL за сваляне на съобщения"},
{"Hide messages flagged BAD","Блокирай съобщения от контакти маркирани BAD"},
{"From","Подател"},
{"Choose file(s) / directory(s) to attach","Избери файли/директории за прикачване"},
{"Select file you want to upload to the","Изберете файл който да качите в "},
{"Hide messages flagged CHECK","Блокирай съобщения маркирани CHECK"},
{"Up","Горе"},
{"Downloads","Долу"},
{"Source","Източник"},
{"Decrease Font Size","Намали размер на фонт"},
{"Configure board","Конфигурирай борд"},
{"Change destination board","Промени борда"},
{"CHK key + filename","CHK ключ + име на файл"},
{"EnableSkins","Включи скинове"},
{"Number of simultaneous uploads","Брой едновременни качвания"},
{"Allow 2 byte characters","Включи двубайтови символи"},
{"Reload selected files","Качи избраните файли"},
{"Automatic saving interval","Интервал на автоматично записване"},
{"Remove all files","Премахни всички файли"},
{"Not available","Не е достъпен"},
{"Set to CHECK","Set to CHECK"},
};
}
