/**
 * Language file for Frost
 *
 * This file has been created automatically.
 * Do NOT edit unless you REALLY know what you're doing!
 *
 * Language: es
 */

package res;

import java.util.ListResourceBundle;

public class LangRes_es extends ListResourceBundle {

public Object[][] getContents() {
    return contents;
}

static final Object[][] contents = {
{"About","Acerca de"},
{"Activate downloading","Activa descarga"},
{"Add attachment(s)","Añade adjunto(s)"},
{"Add Board(s)","Añade Foro(s)"},
{"Add new board","Añade nuevo foro"},
{"Add new folder","Añade nueva carpeta"},
{"Add selected board","Añade el foro seleccionado"},
{"Age","Antigüedad"},
{"all boards","todos los foros"},
{"Allow 2 byte characters","Permite caracteres de 2 bytes"},
{"Archive Extension","Extensiones de Archivo"},
{"Audio Extension","Extensiones de Sonido"},
{"Automatic Indexing","Indexación automática"},
{"Automatic message update","Refresco automático de foros"},
{"Automatic saving interval","Intervalo de grabación automática"},
{"Automatic update options","Opciones de refresco automático"},
{"AvailableSkins","Skins disponibles"},
{"batch explanation","(cuanto mayor más rápido pero menos resistente a spam)"},
{"Block messages with body containing (separate by ';' )","Bloquea mensajes cuyo cuerpo contiene (separados por ';' )"},
{"Block messages with subject containing (separate by ';' )","Bloquea mensajes cuyo asunto contiene (separados por ';' )"},
{"block user (sets to BAD)","bloquea usuario (marca como MALO)"},
{"board","foro"},
{"Board","Foro"},
{"Board Information Window","Ventana de Información de Foros"},
{"BoardInfoFrame.Board information window","Ventana de Información de Foros"},
{"BoardInfoFrame.Boards","Foros"},
{"BoardInfoFrame.Close","Cierra"},
{"BoardInfoFrame.Files","Ficheros"},
{"BoardInfoFrame.Messages","Mensajes"},
{"BoardInfoFrame.Update","Refresca"},
{"BoardInfoFrame.Update all boards","Refresca todos los foros"},
{"BoardInfoFrame.UpdateSelectedBoardButton","Refresca Foro Seleccionado"},
{"Browse","Examina"},
{"Bulgarian","Búlgaro"},
{"Cancel","Cancela"},
{"Change destination board","Cambia foro de destino"},
{"CHK key","clave CHK"},
{"CHK key + filename","clave CHK + nombre de fichero"},
{"Choose background color if updating board is not selected","Escoge el color de fondo para los foros no seleccionados que se están refrescando"},
{"Choose background color if updating board is selected","Escoge el color de fondo para los foros seleccionados que se están refrescando"},
{"Choose boards to attach","Escoge el foro(s) a adjuntar"},
{"Choose file(s) / directory(s) to attach","Escoge el fichero(s) / directorio(s) a adjuntar"},
{"Choose updating color of NON-SELECTED boards","Escoge el color de refresco de los foros NO SELECCIONADOS"},
{"Choose updating color of SELECTED boards","Escoge el color de refresco de los foros SELECCIONADOS"},
{"Clean the keypool","Limpia el pool de claves"},
{"Configure board","Configura foro"},
{"Configure selected board","Configura foro seleccionado"},
{"Copy to clipboard","Copia al portapapeles"},
{"Create message","Crea mensaje"},
{"Cut","Corta"},
{"Cut board","Corta foro"},
{"Date","Fecha"},
{"Decode each segment immediately after its download","Decodifica cada segmento nada más descargarse"},
{"Decrease Font Size","Reduce Tamaño del Fuente"},
{"Default","Por defecto"},
{"Destination","Destino"},
{"Disable all downloads","Desactiva todas las descargas"},
{"Disable downloads","Desactiva descargas"},
{"Disable selected downloads","Desactiva descargas seleccionadas"},
{"Disable splashscreen","Desactiva pantalla de splash"},
{"Disable uploads","Desactiva subidas"},
{"Display","Pantalla"},
{"Display board information window","Muestra ventana de información de foros"},
{"Display known boards","Muestra foros conocidos"},
{"Display list of known boards","Muestra lista de foros conocidos"},
{"Do not trust","No confiar"},
{"Do spam detection","Realiza detección de spam"},
{"Do you want to enter a subject?","¿Quieres introducir un asunto?"},
{"Document Extension","Extensiones de Documento"},
{"Done","Hecho"},
{"Down","Abajo"},
{"Download all keys","Descarga todas las claves"},
{"Download attachment(s)","Descarga adjunto(s)"},
{"Download directory","Directorio para descargas"},
{"Download selected attachment","Descarga el adjunto seleccionado"},
{"Download selected keys","Descarga claves seleccionadas"},
{"Downloads","Descargas"},
{"Dutch","Holandés"},
{"Enable all downloads","Activa todas las descargas"},
{"Enable downloads","Activa descargas"},
{"Enable requesting of failed download files","Activa la petición de ficheros de descargas fallidas"},
{"Enable selected downloads","Activa descargas seleccionadas"},
{"EnableSkins","Activa Skins"},
{"English","Inglés"},
{"Executable Extension","Extensiones Ejecutables"},
{"Exit","Salir"},
{"Experimental Freenet Browser","Navegador Experimental para Freenet"},
{"Failed","Falló"},
{"File","Fichero"},
{"Filename","Nombre del fichero"},
{"Files","Ficheros"},
{"Folder","Carpeta"},
{"folder","carpeta"},
{"French","Francés"},
{"From","De"},
{"Frost by Jantho","Frost por Jantho"},
{"Generate new keypair","Genera nueva pareja de claves"},
{"German","Alemán"},
{"Help","Ayuda"},
{"Help spread files from people marked GOOD","Ayuda a difundir los ficheros de la gente marcada BUENA"},
{"help user (sets to GOOD)","ayuda a usuario (marca como BUENO)"},
{"Hide files from anonymous users","Oculta ficheros de usuarios anónimos"},
{"Hide files from people marked BAD","Oculta ficheros de gente marcada como MALA"},
{"Hide messages flagged BAD","Oculta mensajes marcados como MALO"},
{"Hide messages flagged CHECK","Oculta mensajes marcados como COMPROBAR"},
{"Hide messages flagged N/A","Oculta mensajes marcados como N/A"},
{"Hide unsigned messages","Oculta mensajes sin firmar"},
{"hours","horas"},
{"Image Extension","Extensiones de Imagen"},
{"Increase Font Size","Aumenta Tamaño del Fuente"},
{"Index","Índice"},
{"Index file redundancy","Redundancia en ficheros de índice"},
{"Indexed attachments","Adjuntos indexados"},
{"Invert enabled state for all downloads","Invierte la activación de todas las descargas"},
{"Invert enabled state for selected downloads","Invierte la activación de las descargas seleccionadas"},
{"Italian","Italiano"},
{"Japanese","Japonés"},
{"Key","Clave"},
{"Keyfile download HTL","HTL de descarga de Keyfiles"},
{"Keyfile upload HTL","HTL de subida de Keyfiles"},
{"KnownBoardsFrame.Add board","Añade foro"},
{"KnownBoardsFrame.Close","Cierra"},
{"KnownBoardsFrame.List of known boards","Lista de foros conocidos"},
{"KnownBoardsFrame.Lookup","Busca"},
{"KnownBoardsFrame.Remove board","Elimina foro"},
{"Language","Idioma"},
{"Last upload","Última subida"},
{"list of nodes","Lista separada por comas de nodos a los que tienes acceso por FCP"},
{"Mark ALL messages read","Marca TODOS los mensajes como leídos"},
{"Mark message unread","Marca el mensaje como no leído"},
{"Maximum number of keys to store","Número máximo de claves a guardar"},
{"Maximum number of retries","Número máximo de reintentos"},
{"Maximum search results","Número máximo de resultados de búsqueda"},
{"Message base","Base de mensajes"},
{"Message download HTL","HTL para bajada de mensajes"},
{"Message upload HTL","HTL para subida de mensajes"},
{"MessageBodyFont","Fuente del cuerpo de los mensajes"},
{"Messages","Mensajes"},
{"Messages Today","Mensajes de Hoy"},
{"Minimize to System Tray","Minimiza a la Bandeja del Sistema"},
{"Minimum update interval of a board","Intervalo mínimo de refresco de un foro"},
{"minutes","minutos"},
{"Miscellaneous","Miscelánea"},
{"MoreSkinsAt","Puedes conseguir más skins en"},
{"Never","Nunca"},
{"New board","Nuevo foro"},
{"New folder","Nueva carpeta"},
{"New message","Nuevo mensaje"},
{"New Node Name","Nombre del Nuevo Foro"},
{"News","Noticias"},
{"No 'From' specified!","!No se ha especificado 'Origen'!"},
{"No subject specified!","!No se ha especificado un asunto!"},
{"NoSkinsFound","¡No se han encontrado skins!"},
{"Not available","No disponible"},
{"Number of concurrently updating boards","Número de foros refrescándose a la vez"},
{"Number of days to display","Número de días a mostrar"},
{"Number of days to download backwards","Número de días en los que descargar hacia atrás"},
{"Number of simultaneous downloads","Número de descargas simultáneas"},
{"Number of simultaneous uploads","Número de subidas simultáneas"},
{"Number of splitfile threads","Número de hilos de splitfile"},
{"Off","Apagado"},
{"OK","De acuerdo"},
{"On","Encendido"},
{"Options","Opciones"},
{"Paste","Pega"},
{"Paste board","Pega foro"},
{"Path","Directorio"},
{"Please enter the prefix you want to use for your files.","Por favor, introduce el prefijo que quieres usar para tus ficheros."},
{"Plugins","Plugins"},
{"Preferences","Preferencias"},
{"Preview","Vista previa"},
{"Private key","Clave privada"},
{"Public board","Foro público"},
{"Public key","Clave pública"},
{"redundancy explanation","(todavía no funciona)"},
{"Refresh","Refresca"},
{"RefreshList","Refresca lista"},
{"Reload all files","Sube todos los ficheros"},
{"Reload selected files","Sube los ficheros seleccionados"},
{"Remove","Elimina"},
{"Remove all downloads","Elimina todas las descargas"},
{"Remove all files","Elimina todos los ficheros"},
{"Remove board","Elimina foro"},
{"Remove finished downloads","Elimina las descargas finalizadas"},
{"Remove finished downloads every 5 minutes","Elimina las descargas finalizadas cada 5 minutos"},
{"Remove selected downloads","Elimina descargas seleccionadas"},
{"Remove selected files","Elimina ficheros seleccionados"},
{"Rename folder","Renombra carpeta"},
{"Reply","Contesta"},
{"Request file after this count of retries","Solicita el fichero tras este número de reintentos"},
{"Requested","Pedido"},
{"Restart failed downloads","Reintenta descargas fallidas"},
{"Restart selected downloads","Reanuda descargas seleccionadas"},
{"Restore default filenames for all files","Restaura nombres por defecto para todos los ficheros"},
{"Restore default filenames for selected files","Restaura nombres por defecto para los ficheros seleccionados"},
{"Results","Resultados"},
{"Sample interval","Intervalo de muestreo"},
{"Save message","Graba mensaje"},
{"Save message to disk","Graba mensaje a disco"},
{"Search","Busca"},
{"Secure board","Foro seguro"},
{"Select a message to view its content.","Selecciona un mensaje para ver su contenido."},
{"Select download directory","Escoge el directorio para las descargas"},
{"Select files you want to upload to the","Escoge los ficheros que quieres subir al"},
{"Selected board","Foro seleccionado"},
{"Send message","Envía mensaje"},
{"Set prefix for all files","Establece prefijo para todos los ficheros"},
{"Set prefix for selected files","Establece prefijo para los ficheros seleccionados"},
{"Set to CHECK","Marca como COMPROBAR"},
{"Share Downloads","Comparte descargas"},
{"Should file attachments be added to upload table?","¿Debo añadir los ficheros adjuntos a la tabla de subidas?"},
{"Show board update visualization","Muestra visualmente el refresco de los foros"},
{"Show healing information","Muestra información de reparación"},
{"Show systray icon","Muestra icono en Bandeja del Sistema"},
{"Sign","Firma"},
{"Sign shared files","Firma ficheros compartidos"},
{"Signature","Firma"},
{"Size","Tamaño"},
{"Source","Origen"},
{"Spanish","Español"},
{"splitfile explanation","(cuanto mayor más rápido pero consume más CPU)"},
{"Start encoding of selected files","Inicia la codificación de los ficheros seleccionados"},
{"State","Estado"},
{"Status","Estado"},
{"Subject","Asunto"},
{"Threshold of blocked messages","Umbral de mensajes bloqueados"},
{"TOFDO","TOFDE"},
{"TOFUP","TOFSU"},
{"Translate Frost into another language","Traduce Frost a otro idioma"},
{"Trust","Confía"},
{"Try to download all segments, even if one fails","Intenta descargar todos los segmentos, aunque alguno falle"},
{"Trying","Intentando"},
{"Unknown","Desconocido"},
{"Up","Arriba"},
{"up htl explanation","(cuanto mayor más lento pero más fiable)"},
{"Update","Refresca"},
{"Upload all files","Sube todos los ficheros"},
{"Upload batch size","Tamaño del lote de subidas"},
{"Upload HTL","HTL para subidas"},
{"Upload selected files","Sube ficheros seleccionados"},
{"Uploading","Subiendo"},
{"Uploads","Subidas"},
{"Use editor for writing messages","Usa editor para escribir mensajes"},
{"Video Extension","Extensiones de Vídeo"},
{"Waiting","Esperando"},
{"Waittime after each try","Tiempo de espera tras cada intento"},
{"Welcome message","!Por favor, lee esto!\n\nPara usar Frost, primero debes seleccionar un tema en la ventana de información de foros. Puedes abrir esta ventana con el botón i de arriba. Puedes enviar mensajes y ficheros a gente usando el mismo foro. Probablemente pase un rato hasta que aparezcan los primeros foros (pulsa el botón de refresco)."},
{"You must enter a sender name!","!Debes introducir un nombre de remitente!"},
{"You must enter a subject!","!Debes introducir un asunto!"},
};
}
