/**
 * Language file for Frost
 *
 * This file has been created automatically.
 * Do NOT edit unless you REALLY know what you're doing!
 *
 * Language: de
 */

package res;

import java.util.ListResourceBundle;

public class LangRes_de extends ListResourceBundle {

public Object[][] getContents() {
    return contents;
}

static final Object[][] contents = {
{"(On)","(An)"},
{"Audio Extension:","Audio-Endung:"},
{"Requested","Gesucht"},
{"Number of simultaneous uploads:","Gleichzeitige Uploads:"},
{"Remove selected files","Ausgewählte Dateien entfernen"},
{"Block messages with subject containing (separate by ';' ):","Blockiere Nachrichten die im Titel enthalten (mit ';' trennen):"},
{"Help","Hilfe"},
{"Show board update visualization (on)","Board Update Visualisierung (an)"},
{"Send message","Nachricht senden"},
{"Hide unsigned messages","Unsignierte Nachrichten verstecken"},
{"splitfile explanation","( größer ist schneller, benötigt aber mehr Leistung )"},
{"Waiting","Warte"},
{"Version 20030126","Version 20030126"},
{"New folder","Neues Verzeichnis"},
{"Do spam detection","Spamerkennung an"},
{"Disable downloads","Herunterladen deaktivieren"},
{"Help spread files from people marked GOOD","Mit 'GOOD' markierte Personen unterstützen"},
{"Index","Index"},
{"Activate uploading","Hochladen aktivieren"},
{"Add Board(s)","Forum hinzufügen"},
{"Automatic Indexing","Automatischer Index"},
{"Search","Suchen"},
{"RefreshList","Refresh List"},
{"Download selected keys","Gewählte Dateien herunterladen"},
{"New board","Neues Forum einfügen"},
{"Cut selected board / folder","Forum / Verzeichnis ausschneiden"},
{"Files","Dateien"},
{"Remove","Entfernen"},
{"Video Extension:","Video-Endung:"},
{"Keyfile upload HTL:","Schlüssel hochlade HTL:"},
{"all boards","alle Foren"},
{"Choose file(s) and/or directories to upload","Verzeichnisse und/oder Dateien zum Hochladen auswählen"},
{"From: ","Von: "},
{"Status","Status"},
{"Preview","Vorschau"},
{"Maximum number of retries:","Maxmale Anzahl von Versuchen:"},
{"Node port:","Node Port:"},
{"Sample interval (hours)","Testinterval (Stunden)"},
{"Welcome message","Bitte lesen!\n\nUm Frost benutzen zu können muss zuerst mindestens ein Forum ausgewählt werden. Du kannst eine Übersicht aller aktiven Foren im Forumsinformationsfenster bekommen (i-Button in der Button Leiste). Wenn Du Frost zum ersten mal startest werden wahrscheinlich noch keine Foren vorhanden sein. Nach ein paar Minuten sollten aber einige gefunden werden (auf aktualisieren drücken)."},
{"Block messages with body containing (separate by ';' ):","Blockiere Nachrichten die im Text enthalten (mit ';' trennen):"},
{"Filename","Dateiname"},
{"Boards: ","Foren: "},
{"OK","OK"},
{"No","Nein"},
{"Download all keys","Alle Dateien herunterladen"},
{"Executable Extension:","Executable-Endung:"},
{"AvailableSkins","Vorhandene Skins"},
{"Save message to disk","Nachricht speichern"},
{"Enable requesting of failed download files (on)","Fehlgeschlagene Downloads anfordern (an)"},
{"up htl explanation","( größer ist langsamer, aber zuverlässiger )"},
{"Generate new keypair","Neues Schlüsselpaar erstellen"},
{"Hide files from anonymous users","Dateien vor anonymen Benutzern verbergen"},
{"Uploads","Hochladen"},
{"Remove board","Gewähltes Forum / Verzeichnis entfernen"},
{"(Off)","(Aus)"},
{"Remove finished downloads every 5 minutes.","Fertige Downloads nach 5 Minuten aus der Liste entfernen."},
{"Download","Herunterladen"},
{"   Down: ","   Down: "},
{"   Selected board: ","   Ausgewähltes Forum: "},
{"Search all boards","Alle Foren durchsuchen"},
{"Restore default filenames for selected files","Standard Dateinamen für gewählte Dateien wieder herstellen"},
{"Number of simultaneous downloads:","Gleichzeitge Downloads:"},
{"Threshold of blocked messages","Schwellwert für zu blockierende Nachrichten"},
{"Up: ","Up: "},
{"Secure board","Gesichertes Forum"},
{"Move selected downloads up","Gewählte Dateien an den Anfang der Liste bewegen"},
{"Upload batch size","Batch Größe hochladen"},
{"Number of days to download backwards:","Nachrichtentage herunterladen:"},
{"Increase Font Size","Grössere Schrift"},
{"Sign","Signieren"},
{"Update","Aktualisieren"},
{"   TOFDO: ","   TOFDO: "},
{"Trust","Vertrauen"},
{"Use editor for writing messages: ","Verwende Editor für neue Nachrichten: "},
{"Cut board","Gewähltes Forum / Verzeichnis ausschneiden"},
{"Automatic update","Automatisches aktualisieren"},
{"Board: ","Forum: "},
{"Age","Alter"},
{"Archive Extension:","Archiv-Endung:"},
{"Hide messages flagged N/A","Verstecke Nachrichten die als N/A gekennzeichnet sind"},
{"No subject specified!","Sie haben keinen Betreff angegeben!"},
{"Size","Größe"},
{"Add new board / folder","Neues Forum / Verzeichnis hinzufügen"},
{"HTL","HTL"},
{"Message upload HTL:","Hochlade HTL:"},
{"Try to download all segments, even if one fails (on)","Lade alle Segmente, auch wenn eines fehlschlägt (an)"},
{"News","Nachrichten"},
{"NoSkinsFound","Keine Skins gefunden"},
{"Restart failed downloads","Starte fehlgeschlagene Downloads neu"},
{"Done","Erledigt"},
{"Do not trust","Nicht vertrauen"},
{"Number of days to display:","Nachrichtentage darstellen:"},
{"Retry","Erneut versuchen"},
{"list of nodes","Komma getrennte Liste von Knoten mit FCP Zugriff"},
{"About","Über"},
{"Move selected files down","Gewählte Dateien an das Ende der Liste bewegen"},
{"Board Information Window","Forums Informationen"},
{"Move selected downloads down","Gewählte Dateien an das Ende der Liste bewegen"},
{"Maximum number of keys to store:","Maximaler Schlüsselspeicher:"},
{"Restore default filenames for all files","Standard Dateinamen für alle Dateien wieder herstellen"},
{"I was not able to upload your message.","Die Nachricht konnte nicht hochgeladen werden."},
{"Show healing information","Heilungs Informationen anzeigen"},
{"Do you want to add this board to the public boardlist?\n\n","Willst Du dieses Forum zur öffentlichen Forumsliste hinzufügen?\n\n"},
{"BoardInfoFrame.UpdateSelectedBoardButton","Ausgewähltes Forum aktualisieren"},
{"Move selected files up","Gewählte Dateien an den Anfang der Liste bewegen"},
{"Messages","Nachrichten"},
{"Add public key to this message","Öffentlichen Schlüssel an Nachricht anhängen"},
{"Clean the keypool","Räume den 'keypool' auf"},
{"Request file after this count of retries:","Fordere Dateien nach x Versuchen:"},
{"Subject: ","Betreff: "},
{"Skins","Texturen"},
{"Key","Schlüssel"},
{"Trying","Anfrage"},
{"Invalid key","Ungültiger Schlüssel"},
{"Date","Datum"},
{"Options","Optionen"},
{"Document Extension:","Dokument-Endung:"},
{"block user (sets to BAD)","Benutzer blockieren (auf 'BAD' setzen)"},
{"Display known boards","Bekannte Foren anzeigen"},
{"Index file redundancy","Index Datei Redundanz"},
{"Signature","Signatur"},
{"know about this board AND he will be able to read and\n","dieses Forum lesen und Nachrichten an dieses Forum\n"},
{"Upload of message failed","Hochladen der Nachricht fehlgeschlagen"},
{"Board","Forum"},
{"Message base:","Nachrichten Basis:"},
{"Add files to board","Dateien zu Forum hinzufügen"},
{" announcement."," Bekanntmachung."},
{"Share Downloads","Downloads freigeben"},
{"Block message from/subject containing:","Blocke Nachrichten deren from/subject enthält:"},
{"New messages","Neue Nachrichten"},
{"Uploading","Aktiv"},
{"Miscellaneous","Verschiedenes"},
{"Message download HTL:","Herunterlade  HTL:"},
{"Cancel","Abbruch"},
{"Private key :","Privater Schlüssel :"},
{"Destination","Ziel"},
{"State","Status"},
{"Never","Nie"},
{"Show systray icon","System Tray Icon anzeigen"},
{"Block messages: ","Blockiere Nachrichten: "},
{"Board information","Forum Informationen"},
{"Number of splitfile threads:","Simultane Splitfile Threads:"},
{"Path","Pfad"},
{"Please enter the prefix you want to use for your files.","Bitte gewünschtes Stichwort eingeben."},
{"Copy as attachment to clipboard","Als Attachment ins Clipboard kopieren"},
{"Do you want to enter a subject?","Wollen sie einen Betreff eingeben?"},
{"Disable uploads","Hochladen deaktivieren"},
{"Save message","Nachricht speichern"},
{"Exit","Ende"},
{"Last upload","Hochgeladen am"},
{"Reply","Antworten"},
{"Show only signed messages","Zeige nur signierte Nachrichten"},
{"redundancy explanation","noch nicht implementiert"},
{"   TOFUP: ","   TOFUP: "},
{"Download attachment(s)","Attachments herunterladen"},
{"New message","Neue Nachricht"},
{"Add attachment(s)","Datei(en) anhängen"},
{"Download directory:","Zielverzeichnis:"},
{"Name","Name"},
{"write messages on this board.","Nachricht an Forum schreiben"},
{"Unknown","Unbekannt"},
{"Waittime after each try (min):","Wartezeit nach jedem Versuch (min):"},
{"No spam mode","Spam verhindern"},
{"New Folder","Neues Verzeichnis"},
{"Select download directory.","Zielverzeichnis auswählen."},
{"Minimum update interval of a board (minutes) :","Mindestdauer zwischen Board-Updates (Minuten) :"},
{"File","Datei"},
{"Yes","Ja"},
{"Display list of known boards","Liste bekannter Foren anzeigen"},
{"MessageBodyFont","Zeichensatz für Nachricht"},
{"Reload all files","Alle Dateien hochladen"},
{"Add board","Forum abonnieren"},
{"Node address:","Node Adresse:"},
{"Set prefix for all files","Präfix für alle Dateien festlegen"},
{"Activate downloading","Herunterladen aktivieren"},
{"Rename folder","Gewählten Ordner umbenennen"},
{"Upload HTL:","Hochlade HTL:"},
{"help user (sets to GOOD)","Benutzer unterstützen (auf 'GOOD' setzen)"},
{"Image Extension:","Bild-Endung:"},
{"ATTENTION: If you choose yes EVERY Frost user will\n","ACHTUNG: Wenn Du zustimmst wird JEDER Frost Benutzer\n"},
{"Public key :","Öffentlicher Schlüssel :"},
{"Automatic update options","Einstellungen zum automatischen Update"},
{"Frost by Jantho","Frost von Jantho"},
{"Public board","Öffentliches Forum"},
{"Remove all downloads","Alle Dateien entfernen"},
{"Preferences","Einstellungen"},
{"Maximum HTL:","Maximale HTL:"},
{"New Node Name","Name des neuen Forums"},
{"Paste board / folder","Forum / Verzeichnis einfügen"},
{"Minimum HTL:","Minimale HTL:"},
{"Invalid key.  Key must begin with one of","Ungültiger Schlüssel."},
{"Indexed attachments","Registrierte Attachments"},
{"Subject","Betreff"},
{"Remove selected board","Aktuelles Forum entfernen"},
{"Select a message to view its content.","Bitte eine Nachricht auswählen um ihren Inhalt zu sehen."},
{"Automatic message update","Foren automatisch aktualisieren"},
{"Failed","Fehler"},
{"Keyfile download HTL:","Schlüssel herunterlade HTL:"},
{"Insert request if HTL tops:","Aktive Anfrage senden wenn HTL größer:"},
{"Copy board","Gewähltes Forum / Verzeichnis kopieren"},
{"Configure selected board","Forum konfigurieren"},
{"Remove selected downloads","Ausgewählte Dateien entfernen"},
{"Number of concurrently updating boards:","Anzahl gleichzeitig aufzufrischender Boards:"},
{"Display board information window","Forumsinformationen anzeigen"},
{"Decode each segment immediately after its download","Dekodiere jedes Element sofort nach dem Download"},
{"Set prefix for selected files","Präfix für gewählte Dateien festlegen"},
{"   Files: ","   Dateien: "},
{"Add more boards","Mehr Foren hinzufügen"},
{"Display","Anzeige"},
{"Sign shared files","Angebotene Dateien signieren"},
{"Retry selected downloads","Ausgewählte Dateien erneut herunterladen"},
{"Board settings for ","Forumeinstellungen für "},
{"Remove selected board / folder","Forum / Verzeichnis entfernen"},
{"Block message body containing:","Blocke Nachrichten die enthalten:"},
{"Copyright (c) 2001 Jan-Thomas Czornack","Copyright (c) 2001 Jan-Thomas Czornack"},
{"Create message","Nachricht erstellen"},
{"Browse...","Durchsuchen..."},
{"   Results: ","   Resultate: "},
{"Choose boards to attach","Wähle Boards zum Anhängen aus"},
{"Hide files from people marked BAD","Dateien vor als 'BAD' markierten Leuten verbergen"},
{"Paste board","Clipboard einfügen"},
{"Minimize to System Tray","In die Taskleiste minimieren"},
{"batch explanation","( größer=schneller kleiner=Spamsicher )"},
{"Hide messages flagged BAD","Zeige keine Nachrichten mit BAD-Flag"},
{"Open Source Project","Open Source Project"},
{"   Messages: ","   Nachrichten: "},
{"From","Von"},
{"Choose file(s) / directory(s) to attach","Dateien oder Verzeichnisse auswählen."},
{"Hide messages flagged CHECK","Zeige keine Nachrichten mit CHECK-Flag"},
{"Copy selected board / folder","Forum / Verzeichnis kopieren"},
{"Downloads","Herunterladen"},
{"Decrease Font Size","Kleinere Schrift"},
{"Configure board","Forum konfigurieren"},
{"Change destination board","Zielforum für gewählte Dateien ändern."},
{"Source","Quelle"},
{"EnableSkins","Skins aktivieren"},
{"Allow 2 byte characters","2 Byte Zeichen erlauben"},
{"Reload selected files","Gewählte Dateien hochladen"},
{"Remove all files","Alle Dateien entfernen"},
{"Not available","Nicht vorhanden"},
{"Set to CHECK","Auf 'CHECK' setzen"},
{"German","Deutsch"},
{"Italian","Italienisch"},
{"Translate Frost into another language","Frost in eine andere Sprache übersetzen"},
{"Plugins","Plugins"},
{"English","Englisch"},
{"Experimental Freenet Browser","Experimental Freenet Browser"},
{"French","Französisch"},
{"Dutch","Holländisch"},
{"Japanese","Japanisch"},
{"Language","Sprache"},
{"MoreSkinsAt", "You can get more skins at"},
};
}
