/**
 * Language file for Frost
 *
 * This file has been created automatically.
 * Do NOT edit unless you REALLY know what you're doing!
 *
 * Language: bg
 */

package res;

import java.util.ListResourceBundle;

public class LangRes_bg extends ListResourceBundle {

public Object[][] getContents() {
    return contents;
}

static final Object[][] contents = {
{"About","Относно"},
{"Activate downloading","включи свалянето"},
{"Add attachment(s)","Прикачи файли"},
{"Add Board(s)","Добави борд"},
{"Add new board","Добави нов борд"},
{"Add new folder","Добави нова папка"},
{"Add selected board","Добави избраният борд"},
{"Age","Възраст"},
{"all boards","всички бордове"},
{"Allow 2 byte characters","Включи двубайтови символи"},
{"Archive Extension","разширение на архивни файли"},
{"Audio Extension","Разширение на изпълними файли"},
{"Automatic Indexing","Автоматично индексиране"},
{"Automatic message update","Автоматично обновяване на бордовете"},
{"Automatic saving interval","Интервал на автоматично записване"},
{"Automatic update options","Настройки на автоматичното обновяване"},
{"AvailableSkins","Инсталирани скинове"},
{"batch explanation","по-голям е по-бърз но по-малък е по-спамоусойчив"},
{"Block messages with body containing (separate by ';' )","Блокирай съобщения които съдържат"},
{"Block messages with subject containing (separate by ';' )","Блокирай съобщения чието заглавие съдържа "},
{"block user (sets to BAD)","блокирай потребител (маркира BAD)"},
{"board","борд"},
{"Board","Борд"},
{"Board Information Window","Информация за бордовете"},
{"BoardInfoFrame.Board information window","Board information window"},
{"BoardInfoFrame.Boards","Boards"},
{"BoardInfoFrame.Close","Close"},
{"BoardInfoFrame.Files","Files"},
{"BoardInfoFrame.Messages","Messages"},
{"BoardInfoFrame.Update","Update"},
{"BoardInfoFrame.Update all boards","Update all boards"},
{"BoardInfoFrame.UpdateSelectedBoardButton","Обнови избраният борд"},
{"Browse","Търси.."},
{"Bulgarian","Български"},
{"Cancel","Отказ"},
{"Change destination board","Промени борда"},
{"CHK key","CHK ключ"},
{"CHK key + filename","CHK ключ + име на файл"},
{"Choose boards to attach","Избери бордове за прикачване"},
{"Choose file(s) / directory(s) to attach","Избери файли/директории за прикачване"},
{"Choose updating color of NON-SELECTED boards","Избери цвят на бордове които се обновяват и не са избрани"},
{"Choose updating color of SELECTED boards","Избери цвят за обновяващи се бордове"},
{"Clean the keypool","почистване на keypool-a"},
{"Configure board","Конфигурирай борд"},
{"Configure selected board","Конфигурирайте избраният борд"},
{"Copy to clipboard","Копирай в клипборда"},
{"Create message","Създай съобщение"},
{"Cut","Cut"},
{"Cut board","Отрежи борд"},
{"Date","Дата"},
{"Decode each segment immediately after its download","Декодирай всеки сегмент веднага щом бъде свален"},
{"Decrease Font Size","Намали размер на фонт"},
{"Default","Default"},
{"Destination","Борд"},
{"Disable all downloads","Изключи всички сваляния"},
{"Disable downloads","Забрани сваляния"},
{"Disable selected downloads","Спри избраните сваляния"},
{"Disable splashscreen","Премахни началния екран"},
{"Disable uploads","Изкючи качванията"},
{"Display","Скинове"},
{"Display board information window","Покажи информация за бордовете"},
{"Display known boards","Списък на известните бордове"},
{"Display list of known boards","Покажи списък на известните бордове"},
{"Do not trust","Недоверие"},
{"Do spam detection","Засичане на спам"},
{"Do you want to enter a subject?","Искате ли да дадете заглавие?"},
{"Document Extension","Разширение за документи"},
{"Done","Готов"},
{"Down","Долу"},
{"Download all keys","Свали всички резултати"},
{"Download attachment(s)","Свали прикачените файли"},
{"Download directory","Директория за сваляне"},
{"Download selected attachment","Download selected attachment"},
{"Download selected keys","Свали избраните файли"},
{"Downloads","Сваляния"},
{"Dutch","Dutch"},
{"Enable all downloads","Включи всички сваляния"},
{"Enable downloads","Включване на свалянията"},
{"Enable requesting of failed download files","Включи поръчване на неуспешни сваляния"},
{"Enable selected downloads","Включи избраните сваляния"},
{"EnableSkins","Включи скинове"},
{"English","English"},
{"Executable Extension","Разширение на изпълними файли"},
{"Exit","Изход"},
{"Experimental Freenet Browser","Експериментален Freenet Browser"},
{"Failed","Неуспешен"},
{"File","Файл"},
{"Filename","Име на файл"},
{"Files","Файли"},
{"Folder","Folder"},
{"folder","folder"},
{"French","French"},
{"From","Подател"},
{"Frost by Jantho","Frost by Jantho"},
{"Generate new keypair","Генерирай нов чифт ключове"},
{"German","German"},
{"Help","Помощ"},
{"Help spread files from people marked GOOD","Помагане на файлове на контакти маркирани GOOD"},
{"help user (sets to GOOD)","помогни на потребителя (маркира GOOD)"},
{"Hide files from anonymous users","Не показвай неподписани файлове"},
{"Hide files from people marked BAD","Блокирай файлове от контакти маркирани BAD"},
{"Hide messages flagged BAD","Блокирай съобщения от контакти маркирани BAD"},
{"Hide messages flagged CHECK","Блокирай съобщения маркирани CHECK"},
{"Hide messages flagged N/A","Hide messages flagged N/A"},
{"Hide unsigned messages","Филтрирай неподписани съобщения"},
{"hours","часове"},
{"Image Extension","Разширение за графични файли"},
{"Increase Font Size","Увеличи размера на фонта"},
{"Index","Индекс"},
{"Index file redundancy","Index file redundancy"},
{"Indexed attachments","индексирай прикачените файлове"},
{"Invert enabled state for all downloads","Инвертирай вкл/изкл. на всички сваляния"},
{"Invert enabled state for selected downloads","Инвертирай вкл/изкл на избраните сваляния!"},
{"Italian","Italian"},
{"Japanese","Japanese"},
{"Key","Ключ"},
{"Keyfile download HTL","HTL за сваляне на индекс файл"},
{"Keyfile upload HTL","HTL за качване на индекс файл"},
{"KnownBoardsFrame.Add board","Add board"},
{"KnownBoardsFrame.Close","Close"},
{"KnownBoardsFrame.List of known boards","List of known boards"},
{"KnownBoardsFrame.Lookup","Lookup"},
{"KnownBoardsFrame.Remove board","Remove board"},
{"Language","Language"},
{"Last upload","Последно качване"},
{"list of nodes","Списък на Фрийнет възели до които имате достъп (разделен със запетая)"},
{"Mark ALL messages read","Маркирай всички съобщения като прочетени"},
{"Mark message unread","Маркирай като непрочетено"},
{"Maximum number of keys to store","Максимален брой ключове в keypool-a"},
{"Maximum number of retries","Максимален брой опити"},
{"Maximum search results","Максимален брой резултати"},
{"Message base","База на съобщенията"},
{"Message download HTL","HTL за сваляне на съобщения"},
{"Message upload HTL","HTL за качване на съобщения"},
{"Messages","Съобщения"},
{"Messages Today","Съобщения днес"},
{"Minimize to System Tray","Minimize to System Tray"},
{"Minimum update interval of a board","Минимален интервал на обновяване на бордове"},
{"minutes","минути"},
{"Miscellaneous","Разни"},
{"MoreSkinsAt","Можете да намерите още скинове на адрес"},
{"Never","Никога"},
{"New board","Нов борд"},
{"New folder","НоваПапка"},
{"New message","Ново съобщение"},
{"New Node Name","Име на новия борд"},
{"News","Съобщения"},
{"No 'From' specified!","Не е даден подател!"},
{"No subject specified!","No subject specified!"},
{"NoSkinsFound","Не са намерини скинове!"},
{"Not available","Не е достъпен"},
{"Number of concurrently updating boards","Брой на бордове които се обновяват едновременно "},
{"Number of days to display","Колко дни да се показват"},
{"Number of days to download backwards","Колко дни назад да се обновяват"},
{"Number of simultaneous downloads","Брой едновременни сваляния"},
{"Number of simultaneous uploads","Брой едновременни качвания"},
{"Number of splitfile threads","Брой тредове"},
{"Off","Изкл."},
{"OK","OK"},
{"On","Вкл."},
{"Options","Настройки"},
{"Paste","Paste"},
{"Paste board","Paste board"},
{"Path","път"},
{"Please enter the prefix you want to use for your files.","Дайте префиксът за вашите файли"},
{"Plugins","Модули"},
{"Preferences","Настройки"},
{"Preview","Преглед"},
{"Private key","Частен ключ"},
{"Public board","Публичен борд"},
{"Public key","публичен ключ"},
{"redundancy explanation","not working yet"},
{"Refresh","Refresh"},
{"RefreshList","Обнови списък"},
{"Reload all files","Качи всички файли"},
{"Reload selected files","Качи избраните файли"},
{"Remove","Изтрий"},
{"Remove all downloads","Премахни всички сваляния"},
{"Remove all files","Премахни всички файли"},
{"Remove board","Премахни борд"},
{"Remove finished downloads","Премахни приключилите сваляния"},
{"Remove finished downloads every 5 minutes","Премахване на приключили сваляния всеки пет минути"},
{"Remove selected downloads","Премахни избраните сваляния"},
{"Remove selected files","Премахни избраните файли"},
{"Rename folder","Преименувай папка"},
{"Reply","Отговори"},
{"Request file after this count of retries","Поръчай файла след # опити"},
{"Requested","Поръчан"},
{"Restart failed downloads","Рестартиране на неуспешни сваляния"},
{"Restart selected downloads","Рестартирай израните сваляния"},
{"Restore default filenames for all files","Възтанови оригиналните имена на всички файли"},
{"Restore default filenames for selected files","Възтанови оригиналните имена на избраните файли"},
{"Results","Резултати"},
{"Sample interval","Интервал на семплиране"},
{"Save message","Запиши съобщението"},
{"Save message to disk","Запиши съобщението на диск"},
{"Search","Търси"},
{"Secure board","Защитен борд"},
{"Select a message to view its content.","Изберете съобщение за да видите съдържанието му."},
{"Select download directory","Select download directory"},
{"Select files you want to upload to the","Select files you want to upload to the"},
{"Selected board","Избран борд"},
{"Send message","Изпрати"},
{"Set prefix for all files","Добави префикс на всички файли"},
{"Set prefix for selected files","Добави префикс на избраните файли"},
{"Set to CHECK","Set to CHECK"},
{"set to neutral (CHECK)","set to neutral (CHECK)"},
{"Share Downloads","Индексиране на свалените файли"},
{"Should file attachments be added to upload table?","Добавя прикачените файлове в списъка на качванията"},
{"Show board update visualization","Визуализация на обновяването"},
{"Show healing information","Покажи възтановителна информация"},
{"Show systray icon","покажи икона в систрай-а"},
{"Sign","Подпиши"},
{"Sign shared files","Подписване на индексираните файли"},
{"Signature","Подпис"},
{"Size","Размер"},
{"Source","Източник"},
{"Spanish","Spanish"},
{"splitfile explanation","(Повече е по-бързо но иска повече CPU)"},
{"Start encoding of selected files","Започни кодиране на избраните файли"},
{"State","Състояние"},
{"Status","Статус"},
{"Subject","Заглавие"},
{"Threshold of blocked messages","Брой блокирани съобщения"},
{"TOFDO","TOFDO"},
{"TOFUP","TOFUP"},
{"Translate Frost into another language","Преведи фрост на друг език"},
{"Trust","Доверие"},
{"Try to download all segments, even if one fails","Всички сегменти да бъдат свалени, дори един да не успее"},
{"Trying","Опитвам се..."},
{"Unknown","Неизвестен"},
{"Up","Горе"},
{"up htl explanation","(повече е по-бавно но по-сигурно)"},
{"Update","Обнови"},
{"Upload all files","Качи всички файли"},
{"Upload batch size","Намали размера на фонта"},
{"Upload HTL","HTL на качване"},
{"Upload selected files","Качи избраните файли"},
{"Uploading","Качване"},
{"Uploads","Качвания"},
{"Use editor for writing messages","Use editor for writing messages"},
{"Video Extension","Разширение на видео файли"},
{"Waiting","Чакане"},
{"Waittime after each try","Интервал между опитите"},
{"Welcome message","Please read this!\n\nTo use Frost, you first need to select a topic from the board information window. You can openthis window with the i-button above. You can send messages and files to people using the same board. It will probably take some time until the first boards show up (press the update button)."},
{"You must enter a sender name!","Трябва да дадете име на подател!"},
{"You must enter a subject!","You must enter a subject!"},
};
}
