/**
 * Language file for Frost
 *
 * This file has been created automatically.
 * Do NOT edit unless you REALLY know what you're doing!
 *
 * Language: fr
 */

package res;

import java.util.ListResourceBundle;

public class LangRes_fr extends ListResourceBundle {

public Object[][] getContents() {
    return contents;
}

static final Object[][] contents = {
{"MessageFrame.ConfirmBody2","'.  Êtes-vous sûr que vous voulez attacher la clef privée ? Si vous choisissez NON, seulement la clef publique sera jointe."},
{"up htl explanation","(bigger is slower but more reliable)"},
{"list of nodes 2","(nodeA:portA, nodeB:portB, ...)"},
{"splitfile explanation","(plus grand est plus rapide mais utilise plus de CPU)"},
{"About","A propos"},
{"Access rights","Access rights"},
{"EnableMessageBodyAA","Activer l'anticrénelage pour le corps des messages"},
{"Enable automatic board update","Activer le rafraichissement automatique des forums"},
{"Activate downloading","Activer le téléchargement"},
{"EnableSkins","Activer les Skins"},
{"Enable all downloads","Activer tous les téléchargements"},
{"Enable selected downloads","Activer tous les téléchargements sélectionnés"},
{"Enable downloads","Activer téléchargements"},
{"Maximum message display (days)","Affichage des messages maximum (En jours)"},
{"Display","Afficher"},
{"Display board information window","Afficher la fenetre d' infos des boards"},
{"Display list of known boards","Afficher la liste des boards connues"},
{"Display known boards","Afficher les boards connues"},
{"Age","Age"},
{"Help","Aide"},
{"Help spread files from people marked GOOD","Aider les personnes notés GOOD"},
{"help user (sets to GOOD)","Aider les utilisateurs (noté GOOD)"},
{"KnownBoardsFrame.Add board","Ajouter board"},
{"NewBoardDialog.add","Ajouter Board"},
{"Add selected board","Ajouter la board"},
{"Add new folder","Ajouter un repertoire"},
{"Add new board","Ajouter une board"},
{"NewBoardDialog.title","Ajouter une nouvelle board"},
{"German","Allemand"},
{"English","Anglais"},
{"Cancel","Annuler"},
{"FrostSearchItemObject.Anonymous","Anonyme"},
{"Automatic update options","Appliquer automatiquement les options"},
{"Archive Extension","Archive Extension"},
{"Archives","Archives"},
{"Core.init.NodeNotRunningBody","Assurez-vous que votre noeud fonctionne et que vous avez configuré freenet correctement."},
{"No 'From' specified!","Aucun  'From' est indiqué ! "},
{"No subject specified!","Aucun sujet spécifié!"},
{"NoSkinsFound","Aucune Skins trouvée"},
{"Audio","Audio"},
{"Audio Extension","Audio Extension"},
{"Increase Font Size","Augmentez La Taille de Police"},
{"From","Auteur"},
{"Automatic saving interval","Automatic saving interval"},
{"Allow 2 byte characters","Autoriser les caracteres de 2 octets"},
{"Warning","Avertissement"},
{"Background color if updating board is not selected","Couleur de fond si mettre à jour les forums n'est pas choisie"},
{"Background color if updating board is selected","Couleur de fond si mettre à jour les forums est choisie "},
{"Low","Bas"},
{"Message base","Base de message"},
{"batch explanation","bigger is faster but smaller is spam resistant"},
{"Blocks","Blocks"},
{"Block messages with these attached boards (separate by ';' )","Bloquer les messages ayant ces boards en piece jointe(separate by ';' )"},
{"Block messages with subject containing (separate by ';' )","Bloquer les messages ayant pour sujet (separate by ';' )"},
{"Block messages with body containing (separate by ';' )","Bloquer les messages contenants (separate by ';' )"},
{"block user (sets to BAD)","bloquer les utilisateurs  (noté BAD)"},
{"board","board"},
{"Board","Board"},
{"Board Information Window","Board Information Window"},
{"BoardInfoFrame.Board information window","Board information window"},
{"Board Name","Board name"},
{"Selected board","Board selectionné"},
{"BoardInfoFrame.Boards","Boards"},
{"Experimental Freenet Browser","Browser Expérimental de Freenet"},
{"Bulgarian","Bulgare"},
{"clipboard.Bytes:","Bytes: "},
{"Hide files from anonymous users","Cacher les fichiers des utilisateurs anonymes"},
{"Hide files from people marked BAD","Cacher les fichiers des utilisateurs BAD"},
{"Hide messages flagged BAD","Cacher les messages marqué BAD"},
{"Hide messages flagged CHECK","Cacher les messages marqué CHECK"},
{"Hide messages flagged N/A","Cacher les messages marqué N/A"},
{"Hide unsigned messages","Cacher les messages non signés"},
{"This will not delete messages","Ceci ne supprimera pas de messages"},
{"Change destination board","Change destination board"},
{"Path","Chemin"},
{"Choose","Choisir"},
{"Choose updating color of NON-SELECTED boards","Choisir la couleur utilisé pendant le rafraichissement des boards non-sélectionnées"},
{"Choose updating color of SELECTED boards","Choisir la couleur utilisé pendant le rafraichissement des boards sélectionnées"},
{"Select download directory","Choisir le repertoire de téléchargement"},
{"Choose boards to attach","Choisir les boards à joindre"},
{"Select files you want to upload to the","Choisir les fichiers à upload"},
{"Choose a Font","Choisir une police"},
{"Core.loadIdentities.ChooseName","Choisissez un pseudo, il ne doit pas être obligatoirement unique "},
{"Select a board to view its content.","Choisissez une board pour voir son contenu"},
{"Sort folder","Classer les répertoires"},
{"Clean the keypool","Clean the keypool"},
{"Key","Clef"},
{"Copy keys only","Clef CHK"},
{"Copy keys with filenames","Clef CHK + nom du fichier"},
{"Private key","Clef privée"},
{"Public key","Clef publique"},
{"Encode requested","Coder requested"},
{"Paste","Coller"},
{"Paste board","Coller board"},
{"Color","Couleur"},
{"list of nodes","Comma-separated list of nodes you have FCP access to"},
{"Start encoding of selected files","Commencez le codage des fichiers choisis"},
{"Configure board","Configurer le forum"},
{"Configure selected board","Configurer le forum sélectionné"},
{"KnownBoardsFrame.Lookup","Consulter"},
{"Copy to clipboard","Copier dans le presse papier"},
{"Copy","Copier"},
{"Copy extended info","Copier les informations "},
{"Message Body","Corps de message"},
{"Cut","Couper"},
{"Cut board","Couper board"},
{"Date","Date"},
{"Delete message","Ignorer message"},
{"Last upload","Dernier envoi"},
{"Description","Description"},
{"NewBoardDialog.description","Description (Facultative). Ne mettez pas d'information privée ici :"},
{"BoardSettingsFrame.description","Description:"},
{"Destination","Destination"},
{"Do spam detection","Detecter le Spam"},
{"Development:","Development:"},
{"Decrease Font Size","Diminuez La Taille de Police"},
{"Discard message","Discard message"},
{"Miscellaneous","Divers"},
{"Document Extension","Document Extension"},
{"Documents","Documents"},
{"Down","Down"},
{"DownloadStatusPanel.Downloading","Downloading:"},
{"Decode each segment immediately after its download","Décoder chaque segment juste après son téléchargement"},
{"Decoding segment","Décoder segment"},
{"Default","Défaut "},
{"Set prefix for all files","Définir le préfixe de tous les fichiers"},
{"Set prefix for selected files","Définir le préfixe des fichiers sélectionnés"},
{"Disable splashscreen","Désactiver le splashscreen"},
{"Disable uploads","Désactiver les envois"},
{"Disable downloads","Désactiver les téléchargements"},
{"Failed","Echoué"},
{"Remove selected files","Effacer les fichiers sélectionnés"},
{"Remove selected downloads","Effacer les téléchargements sélectionnés"},
{"Remove all files","Effacer tous les fichiers"},
{"Remove all downloads","Effacer tous les téléchargements"},
{"Waiting","En attente"},
{"redundancy explanation","En devellopement"},
{"FrostSearchItemObject.Offline","En différé"},
{"Enable logging","Enable logging"},
{"Enable requesting of failed download files","Enable requesting of failed download files"},
{"DownloadTableFormat.Enabled","Enabled"},
{"Save message to disk","Enregistrer ce message sur le disque..."},
{"Uploading","Envoi en cours"},
{"Sending IP address to NSA","Envoie l'adresse IP à la DST"},
{"Uploads","Envois"},
{"Send message","Envoyer le message"},
{"Email.address","envoyez message à"},
{"Core.init.NodeNotRunningTitle","Erreur - impossible d' établir une liaison à freenet."},
{"Spanish","Espagnol"},
{"Trying","Essai en cours"},
{"Try to download all segments, even if one fails","Essayez de télécharger tous les segments, même si un échoue"},
{"Executable Extension","Executable Extension"},
{"Executables","Executables"},
{"Trust","Faire confiance"},
{"BoardInfoFrame.Close","Fermer"},
{"KnownBoardsFrame.Close","Fermer"},
{"File","Fichier"},
{"Encoding file","Fichier en cours de codage"},
{"BoardInfoFrame.Files","Fichiers"},
{"Files","Fichiers"},
{"StatusPanel.file","file"},
{"clipboard.File:","File:  "},
{"StatusPanel.files","files"},
{"Public board","Forum publique"},
{"Secure board","Forum sécurisé"},
{"News","Forums"},
{"Number of concurrently updating boards","forums mis à jour simultanement"},
{"French","Francais"},
{"Saver.AutoTask.message","Frost a détecté une erreur et c'est fermer automatiquement."},
{"Core.loadIdentities.ConnectionNotEstablishedBody","Frost n'a pas pu établir une connection à freenet. Pour l' installation de Frost et créer votre pseudo une connection est nécessaire, apres vous pouvez lire les messages sans connection. Veuillez vous assurer que vous êtes connecté puis relancez Frost. "},
{"Frost by Jantho","Frost par Jantho"},
{"Frost was not able to upload your message.","Frost ne peux envoyer ce message."},
{"Bold","Gras"},
{"Bold Italic","Gras Italique"},
{"Generate new keypair","Générer une nouvelle paire de clefs"},
{"High","Haut"},
{"hours","heures"},
{"Dutch","Hollandais"},
{"Message upload HTL","HTL d' insertion des messages"},
{"Keyfile upload HTL","HTL d'insertion"},
{"Message download HTL","HTL de Téléchargement des messages"},
{"Keyfile download HTL","HTL de Téléchargement."},
{"Hypercube fluctuating!","Hypercube fluctuating!"},
{"Image Extension","Image Extension"},
{"Images","Images"},
{"MessageFrame.ConfirmTitle","Inclure la clef privée ?"},
{"Unknown","Inconnu"},
{"Index","Index"},
{"Index file redundancy","Index des fichiers Redondants"},
{"Automatic Indexing","Indexage Automatique"},
{"Indexed attachments","Indexed attachments"},
{"Not available","Indisponible"},
{"Minimum update interval of a board","Intervalle minimum de mise à jour d'une board"},
{"Invert enabled state for selected downloads","Inversez l'état permis pour les téléchargements sélectionnés"},
{"Invert enabled state for all downloads","Inversez l'état pour tous les téléchargements"},
{"Italian","Italien"},
{"Italic","Italique"},
{"Never","Jamais"},
{"Japanese","Japonais"},
{"Add attachment(s)","Joindre"},
{"Add Board(s)","Joindre Board(s)"},
{"Key not available yet","Clef pas encore disponible"},
{"clipboard.Key:","Clef::   "},
{"Core.loadIdentities.ConnectionNotEstablishedTitle","La connection a Freenet a échouée"},
{"Language","Langue"},
{"Less","Less"},
{"File List","Liste de fichier"},
{"Message List","Liste de Message"},
{"KnownBoardsFrame.List of known boards","Liste des boards connus"},
{"Log file size limit (in KB)","Limiter la taille du fichier Log  (en KB)"},
{"Logging level","Niveau de Logging"},
{"Mark message unread","Marquer  message non-lu"},
{"Mark ALL messages read","Marquer TOUS LES messages lus"},
{"BoardInfoFrame.Messages","Messages"},
{"Messages","Messages"},
{"Messages Today","Messages d'Aujourd'hui"},
{"Update","Mettre à jour"},
{"Medium","Milieu"},
{"minutes","minutes"},
{"Misc code contributions:","Misc code contributions:"},
{"Override default settings","Modifier les parametres par defaut"},
{"More","More"},
{"SMTP.password","mot de passe"},
{"Do not trust","Ne pas faire confiance"},
{"Core.init.TransientNodeTitle","Noeud transient detecté"},
{"KnownBoardsTableModel.Boardname","Nom de la Board"},
{"Filename","Nom du fichier"},
{"NewBoardDialog.name","Nom:"},
{"Number of simultaneous uploads","Nombre d'insertions simultanés"},
{"Number of days to display","Nombre de jours d'affichage"},
{"Number of splitfile threads","Nombre de splitfile threads"},
{"Number of simultaneous downloads","Nombre de téléchargements simultanés"},
{"Maximum number of retries","Nombre maximum de nouvelles tentatives"},
{"Maximum number of keys to store","Nombre maximum des clefs stockées"},
{"No","Non"},
{"Create message","Nouveau message"},
{"New message","Nouveau message"},
{"New Node Name","Nouveau nom de Board"},
{"New Folder Name","Nouveau nom de repertoire"},
{"New folder","Nouveau repertoire"},
{"newfolder","Nouveau repertoire"},
{"New board","Nouvelle board"},
{"newboard","Nouvelle Board"},
{"Number of days to download backwards","Number of days to download backwards"},
{"Off","Off"},
{"OK","Ok"},
{"On","On"},
{"Open Source Project (GPL license)","Open Source Project (GPL license)"},
{"Settings for board","Option de la board"},
{"Options","Options"},
{"Yes","Oui"},
{"Browse","Ouvrir"},
{"Share Downloads","Partager les Téléchargements"},
{"BoardSettingsFrame.confirmTitle","Placez cette Board en public ? "},
{"Plain","plaine"},
{"Plugins","Plugins"},
{"Fonts","Polices"},
{"Preview","Preview"},
{"Saver.AutoTask.title","Problem found."},
{"Preferences","Préférences"},
{"SMTP.username","pseudo"},
{"Core.loadIdentities.InvalidNameTitle","Pseudo invalide"},
{"UploadsUnderway.body","Quelques messages sont toujours en envois. Voulez-vous vraiment quitter ?"},
{"Exit","Quitter"},
{"BoardInfoFrame.Update","Rafraichir"},
{"Refresh","Rafraichir"},
{"Automatic message update","Rafraichir automatiquement les forums"},
{"BoardInfoFrame.UpdateSelectedBoardButton","Rafraichir les forums sélectionnées"},
{"RefreshList","Rafraichir Liste"},
{"BoardInfoFrame.Update all boards","Rafraichir tous les forums"},
{"Reaching ridiculous speed...","Reaching ridiculous speed..."},
{"Reload selected files","Recharger les fichiers sélectionnés"},
{"Reload all files","Recharger tous les fichiers"},
{"Search","Recherche"},
{"Restart failed uploads","Relancer les envois loupés"},
{"Silently retry failed messages","Relancer les messages loupés sans PopUp"},
{"Restart failed downloads","Relancer les téléchargements loupés"},
{"Restart selected downloads","Relancer les téléchargements selectionnés"},
{"Rename folder","Renommer repertoire"},
{"Folder","Repertoire"},
{"folder","repertoire"},
{"Request file after this count of retries","Request file after this count of retries"},
{"Requested","Requested"},
{"Requesting","Requesting"},
{"Restore default filenames for all files","Restaurer les noms de fichiers par défaut de tous les fichiers"},
{"Restore default filenames for selected files","Restaurer les noms de fichiers par défaut des fichiers sélectionnés"},
{"Results","Resultats"},
{"Retry","Nouvelle tentative"},
{"Retry on next startup","Nouvelle tentative au prochain demarrage"},
{"Minimize to System Tray","Réduire dans le System Tray"},
{"Download directory","Répertoire de téléchargement"},
{"Reply","Répondre"},
{"Maximum search results","Résultats maximum de recherche"},
{"Sample","Sample"},
{"Save message","Sauvegarder le message"},
{"SMTP.server","server address"},
{"Set to","Set to"},
{"Set to CHECK","Set to CHECK"},
{"set to neutral (CHECK)","set to neutral (CHECK)"},
{"Threshold of blocked messages","Seuil des messages bloqués "},
{"Should file attachments be added to upload table?","Should file attachments be added to upload table?"},
{"Show healing information","Show healing information"},
{"BoardSettingsFrame.confirmBody","Si vous placez cette Board en public, vous perdrez ses clefs. Êtes-vous sûr de vouloir faire cela ?"},
{"Sig","Sig"},
{"Signature","Signature"},
{"Sign","Signer"},
{"Sign shared files","Signer les fichiers partagés"},
{"AvailableSkins","Skins Disponibles"},
{"Source","Source"},
{"Splash Screen Logo:","Splash Screen Logo:"},
{"Status","Statut"},
{"Disable selected downloads","Stopper les téléchargements sélectionnés"},
{"Disable all downloads","Stopper tous les téléchargements"},
{"Subject","Sujet"},
{"Remove","supprimer"},
{"KnownBoardsFrame.Remove board","Supprimer board"},
{"Remove board","Supprimer board"},
{"Remove finished downloads","Supprimer les téléchargements finis"},
{"Remove finished downloads every 5 minutes","Supprimer les téléchargements finis toutes les 5 minutes "},
{"System Tray Executables:","System Tray Executables:"},
{"Choose file(s) / directory(s) to attach","Sélectionnez le(s) fichier(s) / dossier(s) à joindre"},
{"Select a message to view its content.","Sélectionnez un message pour voir son contenu."},
{"Size","Taille"},
{"Waittime after each try","Temps d'attente après chaque essai"},
{"Done","Terminé"},
{"Frost.lockFileFound","This indicates that another Frost instance is already running in this directory.\nRunning Frost concurrently will cause data loss.\nIf you are REALLY SURE that Frost is not already running, delete the lockfile:\n"},
{"TOFDO","TOFDO"},
{"TOFUP","TOFUP"},
{"All files","Tous les fichiers"},
{"Sample interval","Toutes les"},
{"all boards","Toutes les boards"},
{"Translate Frost into another language","Traduire Frost en une autre langue"},
{"Translation Support:","Translation Support:"},
{"Tries","Tries"},
{"Very low","Très bas"},
{"Very high","Très haut"},
{"SearchTableFormat.Downloading","Téléchargement "},
{"Pause downloading","Téléchargement en pause"},
{"Downloads","Téléchargements"},
{"Download attachment(s)","Télécharger la(les) pièce(s) jointe(s)"},
{"Download selected attachment","Télécharger la(les) pièce(s) jointe(s) sélectionnée(s)"},
{"Download selected keys","Télécharger les clefs sélectionnées"},
{"Download all keys","Télécharger toutes les clefs"},
{"SearchTableFormat.Downloaded","Téléchargé"},
{"You must enter a subject!","Un sujet est indispensable"},
{"Undelete message","Undelete message"},
{"Initializing Mainframe","Unité centrale d'Initialisation"},
{"Up","Up"},
{"Upload batch size","Upload batch size"},
{"Upload HTL","Upload HTL"},
{"Upload of message failed","Upload of message failed"},
{"Upload selected files","Uploader les fichiers selectionnés"},
{"Upload all files","Uploader tous les fichiers"},
{"SearchTableFormat.Uploading","Uploading"},
{"UploadStatusPanel.Uploading","Uploading:"},
{"UploadsUnderway.title","Uploads en cours"},
{"Use default","Use default"},
{"Use editor for writing messages","Utiliser un editeur de texte pour ecrire les messages"},
{"Version","Version"},
{"Please choose a new name","Veuillez choisir un nouveau nom"},
{"Please enter the prefix you want to use for your files.","Veuillez entrer le préfixe que vous voulez utiliser pour vos fichiers:"},
{"NewBoardDialog.details","Veuillez entrer les détails de la nouvelle board:"},
{"Welcome message","Veuillez lire ceci !  To use Frost, you first need to select a topic from the board information window. You can openthis window with the i-button above. You can send messages and files to people using the same board. It will probably take some time until the first boards show up (press the update button)."},
{"Please enter a name for the new board","Veuillez écrire un nom pour la nouvelle board"},
{"Please enter a name for the new folder","Veuillez écrire un nom pour le nouveau répertoire"},
{"Video","Video"},
{"Video Extension","Video Extension"},
{"Show systray icon","Voir l'icone SysTray"},
{"Show board update visualization","Voir la mise à jour de la board"},
{"Show deleted messages","Voir les messages ignorés"},
{"Core.init.TransientNodeBody","Votre noeud est TRANSIENT. Un PERMANENT est meuilleur pour freenet."},
{"Core.loadIdentities.InvalidNameBody","Votre pseudo ne doit pas contenir '@ '!"},
{"Do you want to enter a subject?","Voulez-vous entrer un sujet?"},
{"Do you really want to overwrite it?","Voulez-vous vraiment l'écraser"},
{"You already have a board with name","Vous avez déjà une board avec ce nom"},
{"You must enter a sender name!","Vous devez écrire un nom d'expéditeur ! "},
{"MoreSkinsAt","Vous pouvez obtenir plus de skins à"},
{"Wasting more time","Wasting more time"},
{"Windows Installer:","Windows Installer:"},
{"MessageFrame.ConfirmBody1","You have the private key to board '"},
{"Email.body","Écrivez le corps de l'email. Le '<nom de fichier>' sera remplacé avec le nom du dossier"},
{"State","État"},
};
}
