package frost.installer;

import java.awt.*;
import java.awt.event.*;
import java.awt.event.ActionListener;
import java.io.*;
import java.io.IOException;
import java.net.URL;
import java.util.Enumeration;

import javax.swing.*;
import javax.swing.JApplet;
import javax.swing.event.*;
import javax.swing.event.DocumentListener;
/**
 * @author Administrator
 *
 * To change the template for this generated type comment go to
 * Window&gt;Preferences&gt;Java&gt;Code Generation&gt;Code and Comments
 */
/**
 * This applet will install Frost
 *
 * @pattern Applet
 *
 * @generatedBy CodePro Studio at 1/6/04 1:11 PM
 *
 * @author Administrator
 *
 * @version $Revision$
 */
public class InstallerApplet extends JApplet {
	private JPanel jPanel = null;
	private GreetingPanel greetingPanel = null;
	private LicensePanel licensePanel = null;
	private LocationPanel locationPanel = null;
	
	
	/**
	 * Returns information about this applet.
	 *
	 * @return a string of information about this applet
	 */
	public String getAppletInfo() {
		return "This applet will install Frost";
	}

	/**
	 * Initializes the applet.
	 *
	 * @see #start
	 * @see #stop
	 * @see #destroy
	 */
	public void init() {
		super.init();
		setContentPane(getJPanel());
		setSize(500, 340);
		getJPanel().add(getGreetingPanel());
	}

	/**
	 * 
	 */
	void greetingNextButtonPressed() {
		getJPanel().remove(getGreetingPanel());
		getJPanel().add(getLicensePanel());
		getLicensePanel().doLayout();
		getJPanel().repaint();
	} 

	/**
	 * 
	 */
	void licenseBackButtonPressed() {
		getJPanel().remove(getLicensePanel());
		getJPanel().add(getGreetingPanel());
		getJPanel().repaint();
	}
	
	/**
	 * 
	 */
	void locationBackButtonPressed() {
		getJPanel().remove(getLocationPanel());
		getJPanel().add(getLicensePanel());
		getJPanel().repaint();
	}
	
	/**
	 * 
	 */
	void locationInstallButtonPressed() {
		// TODO Auto-generated method stub

	}

	/**
	 * 
	 */
	void licenseAgreeButtonPressed() {
		getJPanel().remove(getLicensePanel());
		getJPanel().add(getLocationPanel());
		getLocationPanel().doLayout();
		getJPanel().repaint();
	}

	/**
	 * This method initializes jPanel
	 * 
	 * @return javax.swing.JPanel
	 */
	private JPanel getJPanel() {
		if(jPanel == null) {
			jPanel = new JPanel();
		}
		return jPanel;
	}
	/**
	 * @return
	 */
	private GreetingPanel getGreetingPanel() {
		if (greetingPanel == null) {
			greetingPanel = new GreetingPanel(this);	
			greetingPanel.setLogoURL(getClass().getResource("/res/logo.png"));
			greetingPanel.initialize();
		}
		return greetingPanel;
	}

	/**
	 * @return
	 */
	private LicensePanel getLicensePanel() {
		if (licensePanel == null) {
			licensePanel = new LicensePanel(this);
			licensePanel.setLicenseURL(getClass().getResource("/res/gpl.txt"));
			licensePanel.initialize();
		}
		return licensePanel;
	}

	/**
	 * @return
	 */
	private LocationPanel getLocationPanel() {
		if (locationPanel == null) {
			locationPanel = new LocationPanel(this);
			String path = System.getProperty("user.home") + System.getProperty("file.separator") + "Frost";
			File pathFile = new File(path);
			try {
				path = pathFile.getCanonicalPath();
			} catch (Exception e) {
				//If it can't get the canonical path, the normal one will have to do.
			}
			locationPanel.setPath(path);
			locationPanel.initialize();
		}
		return locationPanel;
	}

}  //  @jve:visual-info  decl-index=0 visual-constraint="10,10"

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.appletPattern
 * strategyId = com.instantiations.assist.eclipse.pattern.appletPattern.applet
 * appletClass = InstallerApplet
 * appletInfo = This applet will ask the user where Frost is going to be installed. After that, it will download the jnlp file from the server into that directory. Then, it will redirect the browser to that jnlp file so that the JWS installation can proceed
 * appletStyle = &Swing based
 * appletStyle.index = 0
 * awtSuperclassType = java.applet.Applet
 * createMain = false
 * createMain.index = 1
 * createThread = false
 * createThread.index = 1
 * destroyMethod = false
 * keyboardEvents = false
 * mouseEvents = false
 * mouseMovementEvents = false
 * package = frost.installer
 * package.sourceFolder = frost-contrib/Installer
 * paramList.count = 0
 * startMethod = false
 * stopMethod = false
 * swingSuperclassType = javax.swing.JApplet
 * writeExample = false
 */